import type { QuizAnswerKeyInventoryItem } from './types';

export const QUIZ_ANSWER_KEY_INVENTORY: readonly QuizAnswerKeyInventoryItem[] = [
  {
    type: 'SINGLE_CHOICE',
    learnerSafeFields: ['type', 'stem', 'options', 'settings'],
    answerKeyFields: ['type', 'correctOptionId'],
    structuredAnswerFields: ['selectedOptionIds'],
    gradingSupport: 'deterministic',
  },
  {
    type: 'MULTIPLE_CHOICE',
    learnerSafeFields: ['type', 'stem', 'options', 'selectionLimit', 'settings'],
    answerKeyFields: ['type', 'correctOptionIds'],
    structuredAnswerFields: ['selectedOptionIds'],
    gradingSupport: 'deterministic',
  },
  {
    type: 'TRUE_FALSE',
    learnerSafeFields: ['type', 'stem', 'settings'],
    answerKeyFields: ['type', 'correctAnswer'],
    structuredAnswerFields: ['selectedOptionIds'],
    gradingSupport: 'deterministic',
  },
  {
    type: 'FILL_IN_THE_BLANK',
    learnerSafeFields: ['type', 'stem', 'blanks', 'settings'],
    answerKeyFields: ['type', 'blanks.id', 'blanks.input.answerKey'],
    structuredAnswerFields: ['textAnswers'],
    gradingSupport: 'deterministic',
  },
  {
    type: 'SHORT_ANSWER',
    learnerSafeFields: ['type', 'stem', 'settings'],
    answerKeyFields: ['type', 'acceptedAnswers', 'caseSensitive'],
    structuredAnswerFields: ['textAnswers'],
    gradingSupport: 'deterministic',
  },
  {
    type: 'ESSAY',
    learnerSafeFields: ['type', 'stem', 'minWordCount', 'maxWordCount', 'showWordCount', 'settings'],
    answerKeyFields: ['type', 'correctAnswer', 'correctAnswerPlain', 'requireFormatting'],
    structuredAnswerFields: ['textAnswers'],
    gradingSupport: 'manual',
  },
  {
    type: 'MATCHING',
    learnerSafeFields: ['type', 'stem', 'pairs.id', 'pairs.left', 'rightOptions', 'settings'],
    answerKeyFields: ['type', 'pairs.id', 'pairs.right'],
    structuredAnswerFields: ['selectedOptionIds'],
    gradingSupport: 'deterministic',
  },
  {
    type: 'ORDERING',
    learnerSafeFields: ['type', 'stem', 'items.id', 'items.text', 'settings'],
    answerKeyFields: ['type', 'items.id', 'items.correctPosition'],
    structuredAnswerFields: ['ordering'],
    gradingSupport: 'deterministic',
  },
  {
    type: 'CATEGORIZATION',
    learnerSafeFields: ['type', 'stem', 'categories', 'items.id', 'items.text', 'settings'],
    answerKeyFields: ['type', 'items.id', 'items.correctCategoryIds'],
    structuredAnswerFields: ['categorizations'],
    gradingSupport: 'deterministic',
  },
  {
    type: 'RATING',
    learnerSafeFields: ['type', 'stem', 'scale', 'settings'],
    answerKeyFields: ['type', 'correctRating'],
    structuredAnswerFields: ['rating'],
    gradingSupport: 'unsupported',
    notes: 'Only deterministic when correctRating is configured.',
  },
  {
    type: 'NUMERIC',
    learnerSafeFields: ['type', 'stem', 'variables', 'formula', 'decimalPlaces', 'settings'],
    answerKeyFields: ['type', 'formula', 'toleranceType', 'tolerance'],
    structuredAnswerFields: ['textAnswers'],
    gradingSupport: 'unsupported',
  },
  {
    type: 'FORMULA',
    learnerSafeFields: ['type', 'stem', 'variables', 'decimalPlaces', 'settings'],
    answerKeyFields: ['type', 'formula', 'toleranceType', 'tolerance'],
    structuredAnswerFields: ['textAnswers'],
    gradingSupport: 'unsupported',
  },
  {
    type: 'HOTSPOT',
    learnerSafeFields: ['type', 'stem', 'imageAssetUri', 'imageWidth', 'imageHeight', 'settings'],
    answerKeyFields: ['type', 'imageWidth', 'imageHeight', 'hotspots'],
    structuredAnswerFields: ['textAnswers'],
    gradingSupport: 'deterministic',
  },
  {
    type: 'HIGHLIGHT',
    learnerSafeFields: ['type', 'stem', 'plainText', 'settings'],
    answerKeyFields: ['type', 'highlights'],
    structuredAnswerFields: ['textAnswers'],
    gradingSupport: 'deterministic',
  },
];
