packages:
  # Applications
  - "apps/*"

  # Shared libraries
  - "packages/analytics"
  - "packages/client"
  - "packages/common"
  - "packages/cookies"
  - "packages/emception"
  - "packages/errors"
  - "packages/ui"
  - "packages/web3"

  # Tooling (build/dev configs)
  - "packages/tooling/*"

  # Tools & demos
  - "tools/*"
  - "demos/*"
