// <auto-generated />
using System;
using GameGuild.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameGuild.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250930093700_FixDependencyInjectionMigration")]
    partial class FixDependencyInjectionMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameGuild.Modules.Authentication.AuthenticationAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeviceFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("device_fingerprint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("boolean")
                        .HasColumnName("is_successful");

                    b.Property<bool>("IsSuspicious")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_suspicious");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<TimeSpan>("ProcessingTime")
                        .HasColumnType("interval")
                        .HasColumnName("processing_time");

                    b.Property<int>("RiskScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("risk_score");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_authentication_attempts");

                    b.HasIndex("AttemptedAt")
                        .HasDatabaseName("ix_authentication_attempts_attempted_at");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_authentication_attempts_correlation_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_authentication_attempts_created_at");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_authentication_attempts_deleted_at");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_authentication_attempts_email");

                    b.HasIndex("IpAddress")
                        .HasDatabaseName("ix_authentication_attempts_ip_address");

                    b.HasIndex("IsSuccessful")
                        .HasDatabaseName("ix_authentication_attempts_is_successful");

                    b.HasIndex("IsSuspicious")
                        .HasDatabaseName("ix_authentication_attempts_is_suspicious");

                    b.HasIndex("RiskScore")
                        .HasDatabaseName("ix_authentication_attempts_risk_score");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_authentication_attempts_session_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_authentication_attempts_tenant_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_authentication_attempts_user_id");

                    b.HasIndex("Email", "AttemptedAt")
                        .HasDatabaseName("ix_authentication_attempts_email_attempted_at");

                    b.HasIndex("IpAddress", "AttemptedAt")
                        .HasDatabaseName("ix_authentication_attempts_ip_address_attempted_at");

                    b.HasIndex("UserId", "IsSuccessful", "AttemptedAt")
                        .HasDatabaseName("ix_authentication_attempts_user_id_is_successful_attempted_at");

                    b.ToTable("authentication_attempts");
                });

            modelBuilder.Entity("GameGuild.Modules.Authentication.MfaAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsSuccessful")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_successful");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("method");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_mfa_attempts");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_mfa_attempts_created_at");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_mfa_attempts_deleted_at");

                    b.HasIndex("IpAddress")
                        .HasDatabaseName("ix_mfa_attempts_ip_address");

                    b.HasIndex("IsSuccessful")
                        .HasDatabaseName("ix_mfa_attempts_is_successful");

                    b.HasIndex("Method")
                        .HasDatabaseName("ix_mfa_attempts_method");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_mfa_attempts_session_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_mfa_attempts_tenant_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_mfa_attempts_user_id");

                    b.HasIndex("IpAddress", "CreatedAt")
                        .HasDatabaseName("ix_mfa_attempts_ip_address_created_at");

                    b.HasIndex("UserId", "IsSuccessful", "CreatedAt")
                        .HasDatabaseName("ix_mfa_attempts_user_id_is_successful_created_at");

                    b.ToTable("mfa_attempts");
                });

            modelBuilder.Entity("GameGuild.Modules.Authentication.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("replaced_by_token");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("revoked_by_ip");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_refresh_tokens_created_at");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_refresh_tokens_deleted_at");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_expires_at");

                    b.HasIndex("IsRevoked")
                        .HasDatabaseName("ix_refresh_tokens_is_revoked");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_refresh_tokens_tenant_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("GameGuild.Modules.Authentication.TrustedDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AssociatedIpAddresses")
                        .HasColumnType("jsonb")
                        .HasColumnName("associated_ip_addresses");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeviceFingerprint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("device_fingerprint");

                    b.Property<string>("DeviceInfo")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("device_info");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("device_name");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("TrustedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trusted_at");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_trusted_devices");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_trusted_devices_created_at");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_trusted_devices_deleted_at");

                    b.HasIndex("DeviceFingerprint")
                        .HasDatabaseName("ix_trusted_devices_device_fingerprint");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_trusted_devices_expires_at");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_trusted_devices_is_active");

                    b.HasIndex("LastUsedAt")
                        .HasDatabaseName("ix_trusted_devices_last_used_at");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_trusted_devices_tenant_id");

                    b.HasIndex("TrustedAt")
                        .HasDatabaseName("ix_trusted_devices_trusted_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_trusted_devices_user_id");

                    b.HasIndex("UserId", "DeviceFingerprint")
                        .IsUnique()
                        .HasDatabaseName("ix_trusted_devices_user_id_device_fingerprint");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("ix_trusted_devices_user_id_is_active");

                    b.ToTable("trusted_devices");
                });

            modelBuilder.Entity("GameGuild.Modules.Authentication.UserMfaConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BackupCodes")
                        .HasColumnType("jsonb")
                        .HasColumnName("backup_codes");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("EnabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enabled_at");

                    b.Property<int>("FailedAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_attempts");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_enabled");

                    b.Property<bool>("IsSetupComplete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_setup_complete");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<DateTime?>("LockedOutUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_out_until");

                    b.Property<string>("PreferredMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("preferred_method");

                    b.Property<string>("QrCodeSetupData")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("qr_code_setup_data");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TotpSecretKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("totp_secret_key");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_user_mfa_configurations");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_user_mfa_configurations_created_at");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_user_mfa_configurations_deleted_at");

                    b.HasIndex("EnabledAt")
                        .HasDatabaseName("ix_user_mfa_configurations_enabled_at");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("ix_user_mfa_configurations_is_enabled");

                    b.HasIndex("LastUsedAt")
                        .HasDatabaseName("ix_user_mfa_configurations_last_used_at");

                    b.HasIndex("PreferredMethod")
                        .HasDatabaseName("ix_user_mfa_configurations_preferred_method");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_user_mfa_configurations_tenant_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_mfa_configurations_user_id");

                    b.ToTable("user_mfa_configurations");
                });

            modelBuilder.Entity("GameGuild.Modules.Authentication.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccessTokenHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("access_token_hash");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeviceFingerprint")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("device_fingerprint");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("jsonb")
                        .HasColumnName("device_info");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsTrustedDevice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_trusted_device");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Location")
                        .HasColumnType("jsonb")
                        .HasColumnName("location");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("refresh_token");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("TerminatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("terminated_at");

                    b.Property<string>("TerminationReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("termination_reason");

                    b.Property<DateTime?>("TrustedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trusted_at");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_user_sessions");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_user_sessions_created_at");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_user_sessions_deleted_at");

                    b.HasIndex("DeviceFingerprint")
                        .HasDatabaseName("ix_user_sessions_device_fingerprint");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_user_sessions_expires_at");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_user_sessions_is_active");

                    b.HasIndex("IsTrustedDevice")
                        .HasDatabaseName("ix_user_sessions_is_trusted_device");

                    b.HasIndex("LastUsedAt")
                        .HasDatabaseName("ix_user_sessions_last_used_at");

                    b.HasIndex("RefreshToken")
                        .IsUnique()
                        .HasDatabaseName("ix_user_sessions_refresh_token");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_user_sessions_tenant_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_sessions_user_id");

                    b.HasIndex("IpAddress", "CreatedAt")
                        .HasDatabaseName("ix_user_sessions_ip_address_created_at");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("ix_user_sessions_user_id_is_active");

                    b.HasIndex("UserId", "IsTrustedDevice")
                        .HasDatabaseName("ix_user_sessions_user_id_is_trusted_device");

                    b.ToTable("user_sessions");
                });

            modelBuilder.Entity("GameGuild.Modules.Credentials.Credential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Metadata")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("metadata");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("value");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_credentials");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_credentials_created_at");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_credentials_deleted_at");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_credentials_tenant_id");

                    b.HasIndex("UserId", "Type")
                        .HasDatabaseName("ix_credentials_user_id_type");

                    b.ToTable("credentials");
                });

            modelBuilder.Entity("GameGuild.Modules.Localization.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_languages");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_languages_code");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_languages_created_at");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_languages_deleted_at");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasDatabaseName("ix_language_unique_default")
                        .HasFilter("is_default = true");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_languages_name");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_languages_tenant_id");

                    b.ToTable("languages");
                });

            modelBuilder.Entity("GameGuild.Modules.Permissions.ContentTypePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<long>("PermissionFlags1")
                        .HasColumnType("bigint")
                        .HasColumnName("permission_flags1");

                    b.Property<long>("PermissionFlags2")
                        .HasColumnType("bigint")
                        .HasColumnName("permission_flags2");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_content_type_permissions");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_content_type_permissions_created_at");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_content_type_permissions_deleted_at");

                    b.HasIndex(new[] { "ContentType", "TenantId" }, "IX_ContentTypePermissions_ContentType_Tenant")
                        .HasDatabaseName("ix_content_type_permissions_content_type_tenant");

                    b.HasIndex(new[] { "ContentType", "UserId", "TenantId" }, "IX_ContentTypePermissions_ContentType_User_Tenant")
                        .IsUnique()
                        .HasDatabaseName("ix_content_type_permissions_content_type_user_tenant");

                    b.HasIndex(new[] { "ExpiresAt" }, "IX_ContentTypePermissions_ExpiresAt")
                        .HasDatabaseName("ix_content_type_permissions_expires_at");

                    b.HasIndex(new[] { "TenantId" }, "IX_ContentTypePermissions_TenantId")
                        .HasDatabaseName("ix_content_type_permissions_tenant_id");

                    b.HasIndex(new[] { "UserId" }, "IX_ContentTypePermissions_UserId")
                        .HasDatabaseName("ix_content_type_permissions_user_id");

                    b.ToTable("content_type_permissions");
                });

            modelBuilder.Entity("GameGuild.Modules.Permissions.TenantPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<long>("PermissionFlags1")
                        .HasColumnType("bigint")
                        .HasColumnName("permission_flags1");

                    b.Property<long>("PermissionFlags2")
                        .HasColumnType("bigint")
                        .HasColumnName("permission_flags2");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_tenant_permissions");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_tenant_permissions_created_at");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_tenant_permissions_deleted_at");

                    b.HasIndex(new[] { "ExpiresAt" }, "IX_TenantPermissions_ExpiresAt")
                        .HasDatabaseName("ix_tenant_permissions_expires_at");

                    b.HasIndex(new[] { "TenantId" }, "IX_TenantPermissions_TenantId")
                        .HasDatabaseName("ix_tenant_permissions_tenant_id");

                    b.HasIndex(new[] { "UserId" }, "IX_TenantPermissions_UserId")
                        .HasDatabaseName("ix_tenant_permissions_user_id");

                    b.HasIndex(new[] { "UserId", "TenantId" }, "IX_TenantPermissions_User_Tenant")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_permissions_user_tenant");

                    b.ToTable("tenant_permissions");
                });

            modelBuilder.Entity("GameGuild.Modules.Resources.ResourceLocalization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("field_name");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resource_type");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("TenantSettingsId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_settings_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_profile_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_resource_localizations");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_resource_localizations_created_at");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_resource_localizations_deleted_at");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("ix_resource_localizations_language_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_resource_localizations_tenant_id");

                    b.HasIndex("TenantSettingsId")
                        .HasDatabaseName("ix_resource_localizations_tenant_settings_id");

                    b.HasIndex("UserProfileId")
                        .HasDatabaseName("ix_resource_localizations_user_profile_id");

                    b.ToTable("resource_localizations");
                });

            modelBuilder.Entity("GameGuild.Modules.Resources.ResourceQuota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("CurrentUsage")
                        .HasColumnType("bigint")
                        .HasColumnName("current_usage");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long?>("HardLimit")
                        .HasColumnType("bigint")
                        .HasColumnName("hard_limit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastReset")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reset");

                    b.Property<string>("Metadata")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("metadata");

                    b.Property<string>("NotificationThresholds")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("notification_thresholds");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("notifications_enabled");

                    b.Property<int>("Period")
                        .HasColumnType("integer")
                        .HasColumnName("period");

                    b.Property<int?>("ResetDayOfMonth")
                        .HasColumnType("integer")
                        .HasColumnName("reset_day_of_month");

                    b.Property<int?>("ResetDayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("reset_day_of_week");

                    b.Property<TimeSpan?>("ResetTime")
                        .HasColumnType("interval")
                        .HasColumnName("reset_time");

                    b.Property<long?>("SoftLimit")
                        .HasColumnType("bigint")
                        .HasColumnName("soft_limit");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_resource_quotas");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_resource_quotas_created_at");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_resource_quotas_deleted_at");

                    b.HasIndex("TenantId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ix_resource_quotas_tenant_id_type");

                    b.ToTable("resource_quotas");
                });

            modelBuilder.Entity("GameGuild.Modules.Resources.ResourceUsageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<double?>("AveragePerDay")
                        .HasColumnType("double precision")
                        .HasColumnName("average_per_day");

                    b.Property<long>("Count")
                        .HasColumnType("bigint")
                        .HasColumnName("count");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Metadata")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("metadata");

                    b.Property<long?>("PeakUsage")
                        .HasColumnType("bigint")
                        .HasColumnName("peak_usage");

                    b.Property<DateTime?>("PeakUsageDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("peak_usage_date");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_end");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_resource_usage_records");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_resource_usage_records_created_at");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_resource_usage_records_deleted_at");

                    b.HasIndex("TenantId", "Type", "PeriodStart")
                        .HasDatabaseName("ix_resource_usage_records_tenant_id_type_period_start");

                    b.ToTable("resource_usage_records");
                });

            modelBuilder.Entity("GameGuild.Modules.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_tenants_created_at");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_tenants_deleted_at");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_tenants_is_active");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_unique_default")
                        .HasFilter("is_default = true");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("GameGuild.Modules.Tenants.TenantDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsMainDomain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_main_domain");

                    b.Property<bool>("IsSecondaryDomain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_secondary_domain");

                    b.Property<string>("Subdomain")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subdomain");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TopLevelDomain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("top_level_domain");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("UserGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_group_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_tenant_domains");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_tenant_domains_created_at");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_tenant_domains_deleted_at");

                    b.HasIndex("TenantId", "IsMainDomain")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_domains_unique_main")
                        .HasFilter("is_main_domain = true");

                    b.HasIndex("TopLevelDomain", "Subdomain")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_domains_toplevel_subdomain");

                    b.ToTable("tenant_domains", (string)null);
                });

            modelBuilder.Entity("GameGuild.Modules.Tenants.TenantSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("integer")
                        .HasColumnName("access_level");

                    b.Property<bool>("AllowUserRegistration")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_user_registration");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DefaultLanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_language_id");

                    b.Property<string>("DefaultTimezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("UTC")
                        .HasColumnName("default_timezone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("RequireRegistrationApproval")
                        .HasColumnType("boolean")
                        .HasColumnName("require_registration_approval");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_tenant_settings");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_tenant_settings_created_at");

                    b.HasIndex("DefaultLanguageId")
                        .HasDatabaseName("ix_tenant_settings_default_language_id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_tenant_settings_deleted_at");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_settings_tenant_id");

                    b.ToTable("tenant_settings", (string)null);
                });

            modelBuilder.Entity("GameGuild.Modules.UserProfiles.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("integer")
                        .HasColumnName("access_level");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_user_profiles");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_user_profiles_created_at");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_user_profiles_deleted_at");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_user_profiles_tenant_id");

                    b.ToTable("user_profiles");
                });

            modelBuilder.Entity("GameGuild.Modules.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FamilyName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("family_name");

                    b.Property<string>("GivenName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("given_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_users_created_at");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_users_deleted_at");

                    b.HasIndex("EmailAddress")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email")
                        .HasFilter("\"email\" IS NOT NULL");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_users_is_active");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_users_tenant_id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_users_updated_at");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users");
                });

            modelBuilder.Entity("GameGuild.Modules.Authentication.AuthenticationAttempt", b =>
                {
                    b.HasOne("GameGuild.Modules.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .HasConstraintName("fk_authentication_attempts_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GameGuild.Modules.Authentication.MfaAttempt", b =>
                {
                    b.HasOne("GameGuild.Modules.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .HasConstraintName("fk_mfa_attempts_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GameGuild.Modules.Authentication.RefreshToken", b =>
                {
                    b.HasOne("GameGuild.Modules.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .HasConstraintName("fk_refresh_tokens_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GameGuild.Modules.Authentication.TrustedDevice", b =>
                {
                    b.HasOne("GameGuild.Modules.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .HasConstraintName("fk_trusted_devices_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GameGuild.Modules.Authentication.UserMfaConfiguration", b =>
                {
                    b.HasOne("GameGuild.Modules.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .HasConstraintName("fk_user_mfa_configurations_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GameGuild.Modules.Authentication.UserSession", b =>
                {
                    b.HasOne("GameGuild.Modules.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .HasConstraintName("fk_user_sessions_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GameGuild.Modules.Credentials.Credential", b =>
                {
                    b.HasOne("GameGuild.Modules.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .HasConstraintName("fk_credentials_tenants_tenant_id");

                    b.HasOne("GameGuild.Modules.Users.User", "User")
                        .WithMany("Credentials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_credentials_users_user_id");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameGuild.Modules.Localization.Language", b =>
                {
                    b.HasOne("GameGuild.Modules.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .HasConstraintName("fk_languages_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GameGuild.Modules.Permissions.ContentTypePermission", b =>
                {
                    b.HasOne("GameGuild.Modules.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .HasConstraintName("fk_content_type_permissions_tenants_tenant_id");

                    b.HasOne("GameGuild.Modules.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_content_type_permissions_users_user_id");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameGuild.Modules.Permissions.TenantPermission", b =>
                {
                    b.HasOne("GameGuild.Modules.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .HasConstraintName("fk_tenant_permissions_tenants_tenant_id");

                    b.HasOne("GameGuild.Modules.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_tenant_permissions_users_user_id");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameGuild.Modules.Resources.ResourceLocalization", b =>
                {
                    b.HasOne("GameGuild.Modules.Localization.Language", "Language")
                        .WithMany("ResourceLocalizations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resource_localizations_languages_language_id");

                    b.HasOne("GameGuild.Modules.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .HasConstraintName("fk_resource_localizations_tenants_tenant_id");

                    b.HasOne("GameGuild.Modules.Tenants.TenantSettings", null)
                        .WithMany("Localizations")
                        .HasForeignKey("TenantSettingsId")
                        .HasConstraintName("fk_resource_localizations_tenant_settings_tenant_settings_id");

                    b.HasOne("GameGuild.Modules.UserProfiles.UserProfile", null)
                        .WithMany("Localizations")
                        .HasForeignKey("UserProfileId")
                        .HasConstraintName("fk_resource_localizations_user_profiles_user_profile_id");

                    b.Navigation("Language");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GameGuild.Modules.Resources.ResourceQuota", b =>
                {
                    b.HasOne("GameGuild.Modules.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resource_quotas_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GameGuild.Modules.Resources.ResourceUsageRecord", b =>
                {
                    b.HasOne("GameGuild.Modules.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resource_usage_records_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GameGuild.Modules.Tenants.TenantDomain", b =>
                {
                    b.HasOne("GameGuild.Modules.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_domains_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GameGuild.Modules.Tenants.TenantSettings", b =>
                {
                    b.HasOne("GameGuild.Modules.Localization.Language", "DefaultLanguage")
                        .WithMany()
                        .HasForeignKey("DefaultLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_settings_languages_default_language_id");

                    b.HasOne("GameGuild.Modules.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_tenant_settings_tenants_tenant_id");

                    b.Navigation("DefaultLanguage");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GameGuild.Modules.UserProfiles.UserProfile", b =>
                {
                    b.HasOne("GameGuild.Modules.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .HasConstraintName("fk_user_profiles_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GameGuild.Modules.Users.User", b =>
                {
                    b.HasOne("GameGuild.Modules.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .HasConstraintName("fk_users_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GameGuild.Modules.Localization.Language", b =>
                {
                    b.Navigation("ResourceLocalizations");
                });

            modelBuilder.Entity("GameGuild.Modules.Tenants.TenantSettings", b =>
                {
                    b.Navigation("Localizations");
                });

            modelBuilder.Entity("GameGuild.Modules.UserProfiles.UserProfile", b =>
                {
                    b.Navigation("Localizations");
                });

            modelBuilder.Entity("GameGuild.Modules.Users.User", b =>
                {
                    b.Navigation("Credentials");
                });
#pragma warning restore 612, 618
        }
    }
}
