<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="FluentValidation" />
        <PackageReference Include="HotChocolate.AspNetCore" />
        <PackageReference Include="HotChocolate.AspNetCore.Authorization" />
        <PackageReference Include="HotChocolate.Data.EntityFramework" />
        <PackageReference Include="HotChocolate.Types.Analyzers" />
      <ProjectReference Include="..\GameGuild.Social.Posts\GameGuild.Social.Posts.csproj" />
  <ProjectReference Include="..\GameGuild.Notifications\GameGuild.Notifications.csproj" />
</ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\GameGuild.SharedKernel\GameGuild.SharedKernel.csproj" />
        <ProjectReference Include="..\GameGuild.Identity.Context\GameGuild.Identity.Context.csproj" />
        <ProjectReference Include="..\GameGuild.Identity.Users\GameGuild.Identity.Users.csproj" />
        <ProjectReference Include="..\GameGuild.Identity.Tenants\GameGuild.Identity.Tenants.csproj" />
        <ProjectReference Include="..\GameGuild.Identity.Authorization\GameGuild.Identity.Authorization.csproj" />
        <ProjectReference Include="..\GameGuild.Identity.Authentication\GameGuild.Identity.Authentication.csproj" />
        <ProjectReference Include="..\GameGuild.Teams\GameGuild.Teams.csproj" />
        <ProjectReference Include="..\GameGuild.GameJams\GameGuild.GameJams.csproj" />
        <ProjectReference Include="..\GameGuild.Commerce.Products\GameGuild.Commerce.Products.csproj" />
        <ProjectReference Include="..\GameGuild.Assets\GameGuild.Assets.csproj" />
    </ItemGroup>

</Project>
