<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\GameGuild.SharedKernel\GameGuild.SharedKernel.csproj"/>
        <ProjectReference Include="..\GameGuild.Identity.Tenants\GameGuild.Identity.Tenants.csproj"/>
        <ProjectReference Include="..\GameGuild.Identity.Users\GameGuild.Identity.Users.csproj"/>
        <ProjectReference Include="..\GameGuild.Commerce\GameGuild.Commerce.csproj"/>
        <ProjectReference Include="..\GameGuild.Commerce.Payments\GameGuild.Commerce.Payments.csproj"/>
        <ProjectReference Include="..\GameGuild.Notifications\GameGuild.Notifications.csproj"/>
        <ProjectReference Include="..\GameGuild.Resources\GameGuild.Resources.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Commands\"/>
        <Folder Include="Queries\"/>
    </ItemGroup>

</Project>
