'use client';

import { updateCourseNotificationSettings } from '@/lib/learning/actions';
import type { CourseNotificationSettings } from '@/lib/learning/queries/settings';
import { Button } from '@game-guild/ui/components/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@game-guild/ui/components/card';
import { Input } from '@game-guild/ui/components/input';
import { Label } from '@game-guild/ui/components/label';
import { Switch } from '@game-guild/ui/components/switch';
import { Bell, Loader2, Mail } from 'lucide-react';
import { useState, useTransition } from 'react';

type StudentKey = Exclude<keyof CourseNotificationSettings['studentNotifications'], 'classReminders'>;
type InstructorKey = Exclude<keyof CourseNotificationSettings['instructorNotifications'], 'lowRatingThreshold'>;

const studentChannels: Array<{ key: StudentKey; label: string }> = [
  { key: 'enrollmentConfirmation', label: 'Enrollment confirmation' },
  { key: 'courseUpdates', label: 'Course updates' },
  { key: 'newContent', label: 'New content' },
  { key: 'upcomingClasses', label: 'Upcoming classes' },
  { key: 'assignmentDue', label: 'Assignment due dates' },
  { key: 'assessmentResults', label: 'Assessment results' },
  { key: 'certificateReady', label: 'Certificate ready' },
  { key: 'discussionReplies', label: 'Discussion replies' },
];

const instructorChannels: Array<{ key: InstructorKey; label: string }> = [
  { key: 'newEnrollment', label: 'New enrollment' },
  { key: 'newReview', label: 'New review' },
  { key: 'supportTicket', label: 'Support ticket' },
  { key: 'discussionMention', label: 'Discussion mention' },
  { key: 'lowRating', label: 'Low rating alert' },
];

export function NotificationSettingsEditor({ settings }: { settings: CourseNotificationSettings }) {
  const [student, setStudent] = useState(settings.studentNotifications);
  const [instructor, setInstructor] = useState(settings.instructorNotifications);
  const [templates, setTemplates] = useState(settings.templates);
  const [reminders, setReminders] = useState(settings.studentNotifications.classReminders.join(', '));
  const [feedback, setFeedback] = useState<{ type: 'success' | 'error'; text: string } | null>(null);
  const [isPending, startTransition] = useTransition();

  function save() {
    setFeedback(null);
    const classReminders = reminders
      .split(/[ ,;]+/)
      .map(Number)
      .filter(Number.isFinite);

    startTransition(async () => {
      const result = await updateCourseNotificationSettings(settings.courseId, {
        studentNotifications: { ...student, classReminders },
        instructorNotifications: instructor,
        templates,
      });
      setFeedback(result.success
        ? { type: 'success', text: 'Notification settings saved.' }
        : { type: 'error', text: result.error });
    });
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2"><Bell className="size-5" />Notification settings</CardTitle>
        <CardDescription>Control course messages sent to learners and instructors.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-8">
        <section className="space-y-4">
          <div><h2 className="font-semibold">Learner notifications</h2><p className="text-sm text-muted-foreground">Messages generated by enrollment and course activity.</p></div>
          <div className="grid gap-3 md:grid-cols-2">
            {studentChannels.map(({ key, label }) => (
              <div key={key} className="flex items-center justify-between gap-4 rounded-md border p-3">
                <Label htmlFor={`student-${key}`}>{label}</Label>
                <Switch id={`student-${key}`} aria-label={label} checked={student[key]} onCheckedChange={(checked) => setStudent((current) => ({ ...current, [key]: checked }))} />
              </div>
            ))}
          </div>
          <div className="max-w-md space-y-2">
            <Label htmlFor="class-reminders">Class reminder minutes</Label>
            <Input id="class-reminders" value={reminders} onChange={(event) => setReminders(event.target.value)} placeholder="1440, 60, 10" />
            <p className="text-xs text-muted-foreground">Comma-separated lead times before a scheduled class.</p>
          </div>
        </section>

        <section className="space-y-4 border-t pt-6">
          <div><h2 className="font-semibold">Instructor alerts</h2><p className="text-sm text-muted-foreground">Operational signals for the teaching team.</p></div>
          <div className="grid gap-3 md:grid-cols-2">
            {instructorChannels.map(({ key, label }) => (
              <div key={key} className="flex items-center justify-between gap-4 rounded-md border p-3">
                <Label htmlFor={`instructor-${key}`}>{label}</Label>
                <Switch id={`instructor-${key}`} aria-label={label} checked={instructor[key]} onCheckedChange={(checked) => setInstructor((current) => ({ ...current, [key]: checked }))} />
              </div>
            ))}
          </div>
          <div className="max-w-xs space-y-2">
            <Label htmlFor="low-rating-threshold">Low rating threshold</Label>
            <Input id="low-rating-threshold" type="number" min={1} max={5} value={instructor.lowRatingThreshold} onChange={(event) => setInstructor((current) => ({ ...current, lowRatingThreshold: Number(event.target.value) }))} />
          </div>
        </section>

        <section className="space-y-4 border-t pt-6">
          <div className="flex items-center gap-2"><Mail className="size-4" /><h2 className="font-semibold">Email templates</h2></div>
          {templates.map((template, index) => (
            <div key={template.id} className="grid gap-3 rounded-md border p-3 md:grid-cols-[minmax(0,1fr)_auto] md:items-end">
              <div className="space-y-2">
                <Label htmlFor={`template-${template.id}`}>Subject for {template.type}</Label>
                <Input id={`template-${template.id}`} value={template.subject} onChange={(event) => setTemplates((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, subject: event.target.value } : item))} />
              </div>
              <Switch aria-label={`Enable ${template.type} template`} checked={template.enabled} onCheckedChange={(checked) => setTemplates((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, enabled: checked } : item))} />
            </div>
          ))}
        </section>

        {feedback ? <p role={feedback.type === 'success' ? 'status' : 'alert'} className={feedback.type === 'success' ? 'text-sm text-emerald-600' : 'text-sm text-destructive'}>{feedback.text}</p> : null}
        <div className="flex justify-end">
          <Button type="button" onClick={save} disabled={isPending}>
            {isPending ? <Loader2 className="mr-2 size-4 animate-spin" /> : null}
            Save notification settings
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
