name: 💎 Feature Request
description: "Propose a new feature, service, or improvement, prioritize your request with an attached bounty."
title: "[Enhancement]: "
labels: ["enhancement", "triage"]
type: feature
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > **This is the issue template for proposing new features, services, or improvements.**
        > Before proposing a new feature, please check the [existing issues](https://github.com/gameguild-gg/website/issues) to see if has already been requested.

        # 💎 Bounty Program
        You can prioritize the resolution of this issue by adding a bounty through our [Bounty Program](https://console.algora.io/org/GameGuild/bounties/new).

  - type: dropdown
    attributes:
      label: Request Type
      description: Select the type of request you are making.
      options:
        - New Feature
        - New Service
        - Improvement
    validations:
      required: true

  - type: input
    id: route_url
    attributes:
      label: "Route URL"
      description: "Provide a URL demonstrating the issue, if applicable. Or the route URL where the issue occurs."
      placeholder: "https://gameguild.gg/the_route_goes_here"

  - type: textarea
    attributes:
      label: 🚨 Problem statement, Use Case, or Opportunity
      description: Describe the problem, use case, or opportunity that this feature, service, or improvement will address.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 💡 Describe the ideal solution in your perspective
      description: Provide a detailed description of the feature, improvement, or service you are proposing. Be specific about functionality, user experience, or design.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 📈 Impact, Risks and Benefits (Optional)
      description: Describe the potential impact, risks, and benefits of implementing this feature, service, or improvement.

  - type: textarea
    attributes:
      label: 📚 Context and Examples (Optional)
      description: Add any additional context, use cases, design, charts, screenshots or videos that can help explain the feature request.

  - type: textarea
    attributes:
      label: ✅ Acceptance Criteria (Optional)
      description: List the conditions or outcomes that would make this feature request complete.

  - type: textarea
    attributes:
      label: 🖇️ Related Issues (Optional)
      description: If applicable, link any related issues or discussions here.
