version: '2.1'

services:
  unbound-mailcow:
    image: ghcr.io/mailcow/unbound:1.24
    environment:
      - TZ=${TZ}
      - SKIP_UNBOUND_HEALTHCHECK=${SKIP_UNBOUND_HEALTHCHECK:-n}
    volumes:
      - ./data/hooks/unbound:/hooks:Z
      - ./data/conf/unbound/unbound.conf:/etc/unbound/unbound.conf:ro,Z
    restart: always
    tty: true
    networks:
      mailcow-network:
        ipv4_address: ${IPV4_NETWORK:-172.22.1}.254
        aliases:
          - unbound

  redis-mailcow:
    image: redis:7.4.2-alpine
    entrypoint: ["/bin/sh","/redis-conf.sh"]
    volumes:
      - redis-vol-1:/data/
      - ./data/conf/redis/redis-conf.sh:/redis-conf.sh:z
    restart: always
    environment:
      - TZ=${TZ}
      - REDISPASS=${REDISPASS}
      - REDISMASTERPASS=${REDISMASTERPASS:-}
    sysctls:
      - net.core.somaxconn=4096
    networks:
      mailcow-network:
        ipv4_address: ${IPV4_NETWORK:-172.22.1}.249
        aliases:
          - redis

  clamd-mailcow:
    image: ghcr.io/mailcow/clamd:1.70
    restart: always
    depends_on:
      unbound-mailcow:
        condition: service_healthy
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    environment:
      - TZ=${TZ}
      - SKIP_CLAMD=${SKIP_CLAMD:-n}
    volumes:
      - ./data/conf/clamav/:/etc/clamav/:Z
      - clamd-db-vol-1:/var/lib/clamav
    networks:
      mailcow-network:
        aliases:
          - clamd

  rspamd-mailcow:
    image: ghcr.io/mailcow/rspamd:2.2
    stop_grace_period: 30s
    depends_on:
      - redis-mailcow
    environment:
      - TZ=${TZ}
      - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
      - IPV6_NETWORK=${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}
      - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
      - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
      - REDISPASS=${REDISPASS}
      - SPAMHAUS_DQS_KEY=${SPAMHAUS_DQS_KEY:-}
    volumes:
      - ./data/hooks/rspamd:/hooks:Z
      - ./data/conf/rspamd/custom/:/etc/rspamd/custom:z
      - ./data/conf/rspamd/override.d/:/etc/rspamd/override.d:Z
      - ./data/conf/rspamd/local.d/:/etc/rspamd/local.d:Z
      - ./data/conf/rspamd/plugins.d/:/etc/rspamd/plugins.d:Z
      - ./data/conf/rspamd/lua/:/etc/rspamd/lua/:ro,Z
      - ./data/conf/rspamd/rspamd.conf.local:/etc/rspamd/rspamd.conf.local:Z
      - ./data/conf/rspamd/rspamd.conf.override:/etc/rspamd/rspamd.conf.override:Z
      - rspamd-vol-1:/var/lib/rspamd
    restart: always
    hostname: rspamd
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    networks:
      mailcow-network:
        aliases:
          - rspamd

  php-fpm-mailcow:
    image: ghcr.io/mailcow/phpfpm:1.93
    command: "php-fpm -d date.timezone=${TZ} -d expose_php=0"
    depends_on:
      - redis-mailcow
    volumes:
      - ./data/hooks/phpfpm:/hooks:Z
      - ./data/web:/web:z
      - ./data/conf/rspamd/dynmaps:/dynmaps:ro,z
      - ./data/conf/rspamd/custom/:/rspamd_custom_maps:z
      - ./data/conf/dovecot/auth/mailcowauth.php:/mailcowauth/mailcowauth.php:z
      - ./data/web/inc/functions.inc.php:/mailcowauth/functions.inc.php:z
      - ./data/web/inc/functions.auth.inc.php:/mailcowauth/functions.auth.inc.php:z
      - ./data/web/inc/sessions.inc.php:/mailcowauth/sessions.inc.php:z
      - ./data/web/inc/functions.mailbox.inc.php:/mailcowauth/functions.mailbox.inc.php:z
      - ./data/web/inc/functions.ratelimit.inc.php:/mailcowauth/functions.ratelimit.inc.php:z
      - ./data/web/inc/functions.acl.inc.php:/mailcowauth/functions.acl.inc.php:z
      - rspamd-vol-1:/var/lib/rspamd
      - mysql-socket-vol-1:/var/run/mysqld/
      - ./data/conf/sogo/:/etc/sogo/:z
      - ./data/conf/rspamd/meta_exporter:/meta_exporter:ro,z
      - ./data/conf/phpfpm/crons:/crons:z
      - ./data/conf/phpfpm/sogo-sso/:/etc/sogo-sso/:z
      - ./data/conf/phpfpm/php-fpm.d/pools.conf:/usr/local/etc/php-fpm.d/z-pools.conf:Z
      - ./data/conf/phpfpm/php-conf.d/opcache-recommended.ini:/usr/local/etc/php/conf.d/opcache-recommended.ini:Z
      - ./data/conf/phpfpm/php-conf.d/upload.ini:/usr/local/etc/php/conf.d/upload.ini:Z
      - ./data/conf/phpfpm/php-conf.d/other.ini:/usr/local/etc/php/conf.d/zzz-other.ini:Z
      - ./data/conf/dovecot/global_sieve_before:/global_sieve/before:z
      - ./data/conf/dovecot/global_sieve_after:/global_sieve/after:z
      - ./data/assets/templates:/tpls:z
      - ./data/conf/nginx/:/etc/nginx/conf.d/:z
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    environment:
      - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
      - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
      - REDISPASS=${REDISPASS}
      - LOG_LINES=${LOG_LINES:-9999}
      - TZ=${TZ}
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
      - MAILCOW_PASS_SCHEME=${MAILCOW_PASS_SCHEME:-BLF-CRYPT}
      - IMAP_PORT=${IMAP_PORT:-143}
      - IMAPS_PORT=${IMAPS_PORT:-993}
      - POP_PORT=${POP_PORT:-110}
      - POPS_PORT=${POPS_PORT:-995}
      - SIEVE_PORT=${SIEVE_PORT:-4190}
      - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
      - IPV6_NETWORK=${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}
      - SUBMISSION_PORT=${SUBMISSION_PORT:-587}
      - SMTPS_PORT=${SMTPS_PORT:-465}
      - SMTP_PORT=${SMTP_PORT:-25}
      - API_KEY=${API_KEY:-invalid}
      - API_KEY_READ_ONLY=${API_KEY_READ_ONLY:-invalid}
      - API_ALLOW_FROM=${API_ALLOW_FROM:-invalid}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-mailcow-dockerized}
      - SKIP_FTS=${SKIP_FTS:-y}
      - SKIP_CLAMD=${SKIP_CLAMD:-n}
      - SKIP_OLEFY=${SKIP_OLEFY:-n}
      - SKIP_SOGO=${SKIP_SOGO:-n}
      - ALLOW_ADMIN_EMAIL_LOGIN=${ALLOW_ADMIN_EMAIL_LOGIN:-n}
      - MASTER=${MASTER:-y}
      - DEV_MODE=${DEV_MODE:-n}
      - DEMO_MODE=${DEMO_MODE:-n}
      - WEBAUTHN_ONLY_TRUSTED_VENDORS=${WEBAUTHN_ONLY_TRUSTED_VENDORS:-n}
      - CLUSTERMODE=${CLUSTERMODE:-}
      - ADDITIONAL_SERVER_NAMES=${ADDITIONAL_SERVER_NAMES:-}
    restart: always
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.phpfpm_keycloak_sync.schedule: "@every 1m"
      ofelia.job-exec.phpfpm_keycloak_sync.no-overlap: "true"
      ofelia.job-exec.phpfpm_keycloak_sync.command: "/bin/bash -c \"php /crons/keycloak-sync.php || exit 0\""
      ofelia.job-exec.phpfpm_ldap_sync.schedule: "@every 1m"
      ofelia.job-exec.phpfpm_ldap_sync.no-overlap: "true"
      ofelia.job-exec.phpfpm_ldap_sync.command: "/bin/bash -c \"php /crons/ldap-sync.php || exit 0\""
    networks:
      mailcow-network:
        aliases:
          - phpfpm

  sogo-mailcow:
    image: ghcr.io/mailcow/sogo:1.133
    environment:
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - TZ=${TZ}
      - LOG_LINES=${LOG_LINES:-9999}
      - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
      - MAILCOW_PASS_SCHEME=${MAILCOW_PASS_SCHEME:-BLF-CRYPT}
      - ACL_ANYONE=${ACL_ANYONE:-disallow}
      - ALLOW_ADMIN_EMAIL_LOGIN=${ALLOW_ADMIN_EMAIL_LOGIN:-n}
      - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
      - SOGO_EXPIRE_SESSION=${SOGO_EXPIRE_SESSION:-480}
      - SKIP_SOGO=${SKIP_SOGO:-n}
      - MASTER=${MASTER:-y}
      - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
      - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
      - REDISPASS=${REDISPASS}
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    volumes:
      - ./data/hooks/sogo:/hooks:Z
      - ./data/conf/sogo/:/etc/sogo/:z
      - ./data/web/inc/init_db.inc.php:/init_db.inc.php:z
      - ./data/conf/sogo/custom-favicon.ico:/usr/lib/GNUstep/SOGo/WebServerResources/img/sogo.ico:z
      - ./data/conf/sogo/custom-shortlogo.svg:/usr/lib/GNUstep/SOGo/WebServerResources/img/sogo-compact.svg:z
      - ./data/conf/sogo/custom-fulllogo.svg:/usr/lib/GNUstep/SOGo/WebServerResources/img/sogo-full.svg:z
      - ./data/conf/sogo/custom-fulllogo.png:/usr/lib/GNUstep/SOGo/WebServerResources/img/sogo-logo.png:z
      - ./data/conf/sogo/custom-theme.js:/usr/lib/GNUstep/SOGo/WebServerResources/js/theme.js:z
      - ./data/conf/sogo/custom-sogo.js:/usr/lib/GNUstep/SOGo/WebServerResources/js/custom-sogo.js:z
      - mysql-socket-vol-1:/var/run/mysqld/
      - sogo-web-vol-1:/sogo_web
      - sogo-userdata-backup-vol-1:/sogo_backup
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.sogo_sessions.schedule: "@every 1m"
      ofelia.job-exec.sogo_sessions.command: "/bin/bash -c \"[[ $${MASTER} == y ]] && /usr/local/bin/gosu sogo /usr/sbin/sogo-tool -v expire-sessions $${SOGO_EXPIRE_SESSION} || exit 0\""
      ofelia.job-exec.sogo_ealarms.schedule: "@every 1m"
      ofelia.job-exec.sogo_ealarms.command: "/bin/bash -c \"[[ $${MASTER} == y ]] && /usr/local/bin/gosu sogo /usr/sbin/sogo-ealarms-notify -p /etc/sogo/cron.creds || exit 0\""
      ofelia.job-exec.sogo_eautoreply.schedule: "@every 5m"
      ofelia.job-exec.sogo_eautoreply.command: "/bin/bash -c \"[[ $${MASTER} == y ]] && /usr/local/bin/gosu sogo /usr/sbin/sogo-tool update-autoreply -p /etc/sogo/cron.creds || exit 0\""
      ofelia.job-exec.sogo_backup.schedule: "@every 24h"
      ofelia.job-exec.sogo_backup.command: "/bin/bash -c \"[[ $${MASTER} == y ]] && /usr/local/bin/gosu sogo /usr/sbin/sogo-tool backup /sogo_backup ALL || exit 0\""
    restart: always
    networks:
      mailcow-network:
        ipv4_address: ${IPV4_NETWORK:-172.22.1}.248
        aliases:
          - sogo

  dovecot:
    image: ghcr.io/mailcow/dovecot:2.33
    depends_on:
      - mysql-mailcow
    volumes:
      - ./data/hooks/dovecot:/hooks/dovecot:z
      - ./data/conf/dovecot:/etc/dovecot:z
      - ./data/vmail:/var/vmail:z
      - ./data/dkim/txt:/shared/www/dkim/txt:z
      - ./data/dkim/keys:/shared/www/dkim/keys:z
      - ./data/postfix/conf/private:/shared/postfix/private:z
      - ./data/conf/rspamd/custom/bad_senders:/etc/rspamd/custom/bad_senders:ro,z
    environment:
      - TZ=${TZ}
      - LOG_LINES=${LOG_LINES:-9999}
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
      - MAILCOW_PASS_SCHEME=${MAILCOW_PASS_SCHEME:-SSHA}
      - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
      - ALLOW_ADMIN_EMAIL_LOGIN=${ALLOW_ADMIN_EMAIL_LOGIN:-n}
      - MAILDIR_GC_TIME=${MAILDIR_GC_TIME:-7200}
      - ACL_ANYONE=${ACL_ANYONE:-disallow}
      - SKIP_SOLR=${SKIP_SOLR:-y}
      - MAILDIR_SUB=${MAILDIR_SUB:-}
      - MASTER_PASSWORD=${MASTER_PASSWORD:-}
      - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
      - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
    ports:
      - "${IMAP_PORT:-143}:143"
      - "${IMAPS_PORT:-993}:993"
      - "${POP_PORT:-110}:110"
      - "${POPS_PORT:-995}:995"
      - "${SIEVE_PORT:-4190}:4190"
    restart: always
    hostname: ${MAILCOW_HOSTNAME}
    networks:
      mailcow-network:
        aliases:
          - dovecot

  postfix:
    image: ghcr.io/mailcow/postfix:1.80
    volumes:
      - ./data/hooks/postfix:/hooks:Z
      - ./data/conf/postfix:/opt/postfix/conf:z
      - ./data/assets/ssl:/etc/ssl/mail/:ro,z
      - postfix-vol-1:/var/spool/postfix
      - crypt-vol-1:/var/lib/zeyple
      - rspamd-vol-1:/var/lib/rspamd
      - mysql-socket-vol-1:/var/run/mysqld/
    environment:
      - TZ=${TZ}
      - LOG_LINES=${LOG_LINES:-9999}
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
      - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
      - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
      - SPAMHAUS_DQS_KEY=${SPAMHAUS_DQS_KEY:-}
    restart: always
    hostname: ${MAILCOW_HOSTNAME}
    ports:
      - "${SUBMISSION_PORT:-587}:587"
      - "${SMTPS_PORT:-465}:465"
      - "${SMTP_PORT:-25}:25"
    networks:
      mailcow-network:
        aliases:
          - postfix

  mysql-mailcow:
    image: mariadb:10.11
    depends_on:
      - unbound-mailcow
    stop_grace_period: 45s
    volumes:
      - mysql-vol-1:/var/lib/mysql/
      - mysql-socket-vol-1:/var/run/mysqld/
      - ./data/conf/mysql/:/etc/mysql/conf.d/:ro,Z
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DBNAME}
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASSWORD=${DBPASS}
      - MYSQL_INITDB_SKIP_TZINFO=1
    restart: always
    hostname: mysql
    networks:
      mailcow-network:
        ipv4_address: 172.22.1.250
        aliases:
          - mysql

  nginx:
    image: ghcr.io/mailcow/nginx:1.03
    depends_on:
      - sogo-mailcow
      - php-fpm-mailcow
      - redis-mailcow
    volumes:
      - ./data/web:/web:z
      - ./data/conf/nginx:/etc/nginx/conf.d:z
      - ./data/conf/rspamd/dynmaps:/dynmaps:ro,z
      - ./data/assets/ssl:/etc/ssl/mail/:ro,z
      - ./data/dkim/txt:/shared/www/dkim/txt:z
      - ./data/dkim/keys:/shared/www/dkim/keys:z
    environment:
      - TZ=${TZ}
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    restart: always
    hostname: nginx
    networks:
      mailcow-network:
        aliases:
          - nginx

  acme:
    image: ghcr.io/mailcow/acme:1.92
    depends_on:
      - nginx
    volumes:
      - ./data/assets/ssl:/var/lib/acme/:z
      - ./data/assets/ssl-example:/var/lib/ssl-example/:z
      - ./data/conf/nginx/:/etc/nginx/:z
    environment:
      - LOG_LINES=${LOG_LINES:-9999}
      - TZ=${TZ}
      - ADDITIONAL_SAN=${ADDITIONAL_SAN}
      - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
      - LE_STAGING=${LE_STAGING:-n}
      - SKIP_LETS_ENCRYPT=${SKIP_LETS_ENCRYPT:-n}
      - SKIP_IP_CHECK=${SKIP_IP_CHECK:-n}
      - SKIP_HTTP_VERIFICATION=${SKIP_HTTP_VERIFICATION:-n}
      - ONLY_MAILCOW_HOSTNAME=${ONLY_MAILCOW_HOSTNAME:-n}
      - LE_REDIS_HOST=${LE_REDIS_HOST:-redis}
      - LE_REDIS_PORT=${LE_REDIS_PORT:-6379}
    restart: always
    networks:
      mailcow-network:
        aliases:
          - acme

  watchdog:
    image: ghcr.io/mailcow/watchdog:2.08
    volumes:
      - ./data/hooks/watchdog:/hooks/watchdog:z
    environment:
      - TZ=${TZ}
      - LOG_LINES=${LOG_LINES:-9999}
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
      - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
      - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
      - SKIPWATCHTASKS=${SKIPWATCHTASKS:-n}
      - SKIP_SOLR=${SKIP_SOLR:-y}
      - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
    restart: always
    networks:
      mailcow-network:
        aliases:
          - watchdog

networks:
  mailcow-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.1.0/24