version: '2.1'

services:
  unbound-mailcow:
    image: ghcr.io/mailcow/unbound:1.24
    environment:
      - TZ=${TZ}
      - SKIP_UNBOUND_HEALTHCHECK=${SKIP_UNBOUND_HEALTHCHECK:-n}
    volumes:
      - ./data/hooks/unbound:/hooks:Z
      - ./data/conf/unbound/unbound.conf:/etc/unbound/unbound.conf:ro,Z
    restart: always
    tty: true
    networks:
      mailcow-network:
        ipv4_address: ${IPV4_NETWORK:-172.22.1}.254
        aliases:
          - unbound

  redis-mailcow:
    image: redis:7.4.2-alpine
    entrypoint: ["/bin/sh","/redis-conf.sh"]
    volumes:
      - redis-vol-1:/data/
      - ./data/conf/redis/redis-conf.sh:/redis-conf.sh:z
    restart: always
    environment:
      - TZ=${TZ}
      - REDISPASS=${REDISPASS}
      - REDISMASTERPASS=${REDISMASTERPASS:-}
    sysctls:
      - net.core.somaxconn=4096
    networks:
      mailcow-network:
        ipv4_address: ${IPV4_NETWORK:-172.22.1}.249
        aliases:
          - redis

  clamd-mailcow:
    image: ghcr.io/mailcow/clamd:1.70
    restart: always
    depends_on:
      unbound-mailcow:
        condition: service_healthy
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    environment:
      - TZ=${TZ}
      - SKIP_CLAMD=${SKIP_CLAMD:-n}
    volumes:
      - ./data/conf/clamav/:/etc/clamav/:Z
      - clamd-db-vol-1:/var/lib/clamav
    networks:
      mailcow-network:
        aliases:
          - clamd

  rspamd-mailcow:
    image: ghcr.io/mailcow/rspamd:2.2
    stop_grace_period: 30s
    depends_on:
      - redis-mailcow
    environment:
      - TZ=${TZ}
      - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
      - IPV6_NETWORK=${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}
      - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
      - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
      - REDISPASS=${REDISPASS}
      - SPAMHAUS_DQS_KEY=${SPAMHAUS_DQS_KEY:-}
    volumes:
      - ./data/hooks/rspamd:/hooks:Z
      - ./data/conf/rspamd/custom/:/etc/rspamd/custom:z
      - ./data/conf/rspamd/override.d/:/etc/rspamd/override.d:Z
      - ./data/conf/rspamd/local.d/:/etc/rspamd/local.d:Z
      - ./data/conf/rspamd/plugins.d/:/etc/rspamd/plugins.d:Z
      - ./data/conf/rspamd/lua/:/etc/rspamd/lua/:ro,Z
      - ./data/conf/rspamd/rspamd.conf.local:/etc/rspamd/rspamd.conf.local:Z
      - ./data/conf/rspamd/rspamd.conf.override:/etc/rspamd/rspamd.conf.override:Z
      - rspamd-vol-1:/var/lib/rspamd
    restart: always
    hostname: rspamd
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    networks:
      mailcow-network:
        aliases:
          - rspamd

  php-fpm:
    image: mailcow/phpfpm:1.98
    depends_on:
      - redis
    volumes:
      - ./data/hooks/phpfpm:/hooks/phpfpm:z
      - ./data/web:/web:z
      - ./data/dkim/txt:/shared/www/dkim/txt:z
      - ./data/dkim/keys:/shared/www/dkim/keys:z
      - ./data/conf/rspamd/dynmaps:/shared/www/rspamd/dynmaps:rw,z
      - ./data/conf/rspamd/custom:/shared/www/rspamd/custom:ro,z
    environment:
      - TZ=${TZ}
      - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
      - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
      - SUBMISSION_PORT=${SUBMISSION_PORT:-587}
      - IMAP_PORT=${IMAP_PORT:-143}
      - IMAPS_PORT=${IMAPS_PORT:-993}
      - POP_PORT=${POP_PORT:-110}
      - POPS_PORT=${POPS_PORT:-995}
      - SIEVE_PORT=${SIEVE_PORT:-4190}
    restart: always
    networks:
      mailcow-network:
        aliases:
          - phpfpm

  sogo:
    image: mailcow/sogo:1.121
    environment:
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - TZ=${TZ}
      - LOG_LINES=${LOG_LINES:-9999}
      - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
      - MAILCOW_PASS_SCHEME=${MAILCOW_PASS_SCHEME:-SSHA}
      - ACL_ANYONE=${ACL_ANYONE:-disallow}
      - ALLOW_ADMIN_EMAIL_LOGIN=${ALLOW_ADMIN_EMAIL_LOGIN:-n}
      - IMAP_PORT=${IMAP_PORT:-143}
      - IMAPS_PORT=${IMAPS_PORT:-993}
      - SOGO_EXPIRE_SESSION=${SOGO_EXPIRE_SESSION:-480}
    volumes:
      - ./data/hooks/sogo:/hooks/sogo:z
      - ./data/conf/sogo/:/etc/sogo/:z
      - ./data/sogo/:/var/lib/sogo/:z
      - ./data/sogo/userdata:/sogo_user_data/:z
    restart: always
    networks:
      mailcow-network:
        aliases:
          - sogo

  dovecot:
    image: mailcow/dovecot:1.27
    depends_on:
      - mysql-mailcow
    volumes:
      - ./data/hooks/dovecot:/hooks/dovecot:z
      - ./data/conf/dovecot:/etc/dovecot:z
      - ./data/vmail:/var/vmail:z
      - ./data/dkim/txt:/shared/www/dkim/txt:z
      - ./data/dkim/keys:/shared/www/dkim/keys:z
      - ./data/postfix/conf/private:/shared/postfix/private:z
      - ./data/conf/rspamd/custom/bad_senders:/etc/rspamd/custom/bad_senders:ro,z
    environment:
      - TZ=${TZ}
      - LOG_LINES=${LOG_LINES:-9999}
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
      - MAILCOW_PASS_SCHEME=${MAILCOW_PASS_SCHEME:-SSHA}
      - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
      - ALLOW_ADMIN_EMAIL_LOGIN=${ALLOW_ADMIN_EMAIL_LOGIN:-n}
      - MAILDIR_GC_TIME=${MAILDIR_GC_TIME:-7200}
      - ACL_ANYONE=${ACL_ANYONE:-disallow}
      - SKIP_SOLR=${SKIP_SOLR:-y}
      - MAILDIR_SUB=${MAILDIR_SUB:-}
      - MASTER_PASSWORD=${MASTER_PASSWORD:-}
      - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
      - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
    ports:
      - "${IMAP_PORT:-143}:143"
      - "${IMAPS_PORT:-993}:993"
      - "${POP_PORT:-110}:110"
      - "${POPS_PORT:-995}:995"
      - "${SIEVE_PORT:-4190}:4190"
    restart: always
    hostname: ${MAILCOW_HOSTNAME}
    networks:
      mailcow-network:
        aliases:
          - dovecot

  postfix:
    image: mailcow/postfix:1.79
    volumes:
      - ./data/hooks/postfix:/hooks/postfix:z
      - ./data/conf/postfix:/opt/postfix/conf:z
      - ./data/conf/postfix/dynamicmaps:/opt/postfix/conf/dynamicmaps:z
      - ./data/conf/postfix/lua:/opt/postfix/conf/lua:z
      - ./data/conf/postfix/custom/sender_restrictions.pcre:/opt/postfix/conf/sender_restrictions.pcre:ro,z
      - ./data/conf/postfix/custom/recipient_restrictions.pcre:/opt/postfix/conf/recipient_restrictions.pcre:ro,z
      - ./data/conf/postfix/custom/sender_header_filter.pcre:/opt/postfix/conf/sender_header_filter.pcre:ro,z
      - ./data/conf/postfix/custom/sender_login_maps.pcre:/opt/postfix/conf/sender_login_maps.pcre:ro,z
      - ./data/conf/postfix/custom/recipient_bcc_maps.pcre:/opt/postfix/conf/recipient_bcc_maps.pcre:ro,z
      - ./data/conf/postfix/custom/serviceheader_maps.pcre:/opt/postfix/conf/serviceheader_maps.pcre:ro,z
      - ./data/conf/rspamd/custom/bad_senders:/etc/rspamd/custom/bad_senders:ro,z
      - ./data/postfix/conf/private:/opt/postfix/private:z
      - ./data/postfix/conf/cache:/opt/postfix/conf/cache:rw,z
      - ./data/postfix/spool:/var/spool/postfix:z
      - ./data/dkim/txt:/shared/www/dkim/txt:z
      - ./data/dkim/keys:/shared/www/dkim/keys:z
    environment:
      - TZ=${TZ}
      - LOG_LINES=${LOG_LINES:-9999}
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
      - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
      - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
      - SPAMHAUS_DQS_KEY=${SPAMHAUS_DQS_KEY:-}
    restart: always
    hostname: ${MAILCOW_HOSTNAME}
    ports:
      - "${SUBMISSION_PORT:-587}:587"
      - "${SMTPS_PORT:-465}:465"
      - "${SMTP_PORT:-25}:25"
    networks:
      mailcow-network:
        aliases:
          - postfix

  mysql-mailcow:
    image: mariadb:10.5
    depends_on:
      - redis
    stop_grace_period: 45s
    volumes:
      - ./data/db/mysql:/var/lib/mysql/:z
      - ./data/conf/mysql/:/etc/mysql/conf.d/:z
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DBNAME}
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASSWORD=${DBPASS}
      - MYSQL_INITDB_SKIP_TZINFO=1
    restart: always
    hostname: mysql
    networks:
      mailcow-network:
        ipv4_address: 172.22.1.250
        aliases:
          - mysql

  nginx:
    image: nginx:mainline-alpine
    depends_on:
      - sogo
      - php-fpm
      - redis
    volumes:
      - ./data/web:/web:z
      - ./data/conf/nginx:/etc/nginx/conf.d:z
      - ./data/conf/rspamd/dynmaps:/dynmaps:ro,z
      - ./data/assets/ssl:/etc/ssl/mail/:ro,z
      - ./data/dkim/txt:/shared/www/dkim/txt:z
      - ./data/dkim/keys:/shared/www/dkim/keys:z
    environment:
      - TZ=${TZ}
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    restart: always
    hostname: nginx
    networks:
      mailcow-network:
        aliases:
          - nginx

  acme:
    image: mailcow/acme:1.88
    depends_on:
      - nginx
    volumes:
      - ./data/assets/ssl:/var/lib/acme/:z
      - ./data/assets/ssl-example:/var/lib/ssl-example/:z
      - ./data/conf/nginx/:/etc/nginx/:z
    environment:
      - LOG_LINES=${LOG_LINES:-9999}
      - TZ=${TZ}
      - ADDITIONAL_SAN=${ADDITIONAL_SAN}
      - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
      - LE_STAGING=${LE_STAGING:-n}
      - SKIP_LETS_ENCRYPT=${SKIP_LETS_ENCRYPT:-n}
      - SKIP_IP_CHECK=${SKIP_IP_CHECK:-n}
      - SKIP_HTTP_VERIFICATION=${SKIP_HTTP_VERIFICATION:-n}
      - ONLY_MAILCOW_HOSTNAME=${ONLY_MAILCOW_HOSTNAME:-n}
      - LE_REDIS_HOST=${LE_REDIS_HOST:-redis}
      - LE_REDIS_PORT=${LE_REDIS_PORT:-6379}
    restart: always
    networks:
      mailcow-network:
        aliases:
          - acme

  watchdog:
    image: mailcow/watchdog:1.97
    volumes:
      - ./data/hooks/watchdog:/hooks/watchdog:z
    environment:
      - TZ=${TZ}
      - LOG_LINES=${LOG_LINES:-9999}
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
      - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
      - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
      - SKIPWATCHTASKS=${SKIPWATCHTASKS:-n}
      - SKIP_SOLR=${SKIP_SOLR:-y}
      - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
    restart: always
    networks:
      mailcow-network:
        aliases:
          - watchdog

networks:
  mailcow-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.1.0/24