<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>GameGuild.Social.Profiles</AssemblyName>
        <RootNamespace>GameGuild.Social.Profiles</RootNamespace>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\GameGuild.SharedKernel\GameGuild.SharedKernel.csproj" />
        <ProjectReference Include="..\GameGuild.Identity.Context\GameGuild.Identity.Context.csproj" />
        <ProjectReference Include="..\GameGuild.Identity.Users\GameGuild.Identity.Users.csproj" />
        <ProjectReference Include="..\GameGuild.Tags\GameGuild.Tags.csproj" />
        <ProjectReference Include="..\GameGuild.Projects\GameGuild.Projects.csproj" />
        <ProjectReference Include="..\GameGuild.Gamification.Achievements\GameGuild.Gamification.Achievements.csproj" />
        <ProjectReference Include="..\GameGuild.Learning.Certificates\GameGuild.Learning.Certificates.csproj" />
    </ItemGroup>

</Project>
