import { isAssetUri } from "@game-guild/assets"
import {
  FillBlankInputType,
  QuizEntryType,
  type CategorizationEntry,
  type CategorizationItem,
  type EssayEntry,
  type FillBlankField,
  type FillBlankInput,
  type FillInTheBlankEntry,
  type FormulaEntry,
  type HighlightEntry,
  type HighlightSpan,
  type HotspotEntry,
  type MatchingEntry,
  type MatchingPair,
  type MultipleChoiceEntry,
  type NumericEntry,
  type OrderingEntry,
  type OrderingItem,
  type QuizEntry,
  type QuizFeedback,
  type QuizLearnerAttachments,
  type RatingEntry,
  type ShortAnswerEntry,
  type SingleChoiceEntry,
  type TrueFalseEntry,
} from "../questions/question-types"
import type { QuizAnswer } from "../answers/answers"

type LearnerFeedback = Pick<QuizFeedback, "general">

type LearnerEntry<T, Omitted extends keyof T> = Omit<T, Omitted | "feedback" | "attachments"> & {
  feedback?: LearnerFeedback
  attachments?: QuizLearnerAttachments
}

export type QuizAuthoringEntry = QuizEntry
// Practice is intentionally authoring-shaped because grading is disabled in
// this runtime and local correctness is only pedagogical feedback.
export type QuizPracticeEntry = QuizAuthoringEntry
export type QuizSubmissionAnswer = QuizAnswer

export type SingleChoiceLearnerEntry = LearnerEntry<SingleChoiceEntry, "correctOptionId">

export type MultipleChoiceLearnerEntry = LearnerEntry<MultipleChoiceEntry, "correctOptionIds">

export type TrueFalseLearnerEntry = LearnerEntry<TrueFalseEntry, "correctAnswer">

export type FillBlankTextLearnerInput = {
  type: FillBlankInputType.Text
}

export type FillBlankNumberLearnerInput = Omit<
  Extract<FillBlankInput, { type: FillBlankInputType.Number }>,
  "correctValue" | "tolerance"
>

export type FillBlankDropdownLearnerInput = Extract<FillBlankInput, { type: FillBlankInputType.Dropdown }>

export type FillBlankWordBankLearnerInput = Extract<FillBlankInput, { type: FillBlankInputType.WordBank }>

export type FillBlankLearnerInput =
  | FillBlankTextLearnerInput
  | FillBlankNumberLearnerInput
  | FillBlankDropdownLearnerInput
  | FillBlankWordBankLearnerInput

export type FillBlankLearnerField = Omit<FillBlankField, "input"> & {
  input: FillBlankLearnerInput
}

export type FillInTheBlankLearnerEntry = LearnerEntry<FillInTheBlankEntry, "blanks"> & {
  blanks: FillBlankLearnerField[]
}

export type ShortAnswerLearnerEntry = LearnerEntry<
  ShortAnswerEntry,
  "acceptedAnswers" | "caseSensitive"
>

export type EssayLearnerEntry = LearnerEntry<
  EssayEntry,
  "correctAnswer" | "correctAnswerPlain" | "requireFormatting"
>

export type MatchingLearnerPair = Pick<MatchingPair, "id" | "left">

export type MatchingLearnerEntry = LearnerEntry<
  MatchingEntry,
  "pairs" | "rightOptions" | "distractors"
> & {
  pairs: MatchingLearnerPair[]
  rightOptions: string[]
}

export type OrderingLearnerItem = Pick<OrderingItem, "id" | "text">

export type OrderingLearnerEntry = LearnerEntry<OrderingEntry, "items"> & {
  items: OrderingLearnerItem[]
}

export type CategorizationLearnerItem = Pick<CategorizationItem, "id" | "text">

export type CategorizationLearnerEntry = LearnerEntry<CategorizationEntry, "items"> & {
  items: CategorizationLearnerItem[]
}

export type RatingLearnerEntry = LearnerEntry<RatingEntry, "correctRating">

export type NumericLearnerEntry = LearnerEntry<NumericEntry, "toleranceType" | "tolerance">

export interface FormulaLearnerPrompt {
  // Generated by the server for grading-enabled formula runtime. It gives the
  // learner enough data to answer without exposing the hidden formula.
  variables: Record<string, number>
  expectedResult: number
  decimalPlaces?: number
}

export type FormulaLearnerEntry = LearnerEntry<
  FormulaEntry,
  "formula" | "toleranceType" | "tolerance"
> & {
  prompt?: FormulaLearnerPrompt
}

export type HotspotLearnerEntry = LearnerEntry<HotspotEntry, "hotspots">

export type HighlightLearnerEntry = LearnerEntry<HighlightEntry, "sourceText" | "highlights">

export type QuizLearnerEntry =
  | SingleChoiceLearnerEntry
  | MultipleChoiceLearnerEntry
  | TrueFalseLearnerEntry
  | FillInTheBlankLearnerEntry
  | ShortAnswerLearnerEntry
  | EssayLearnerEntry
  | MatchingLearnerEntry
  | OrderingLearnerEntry
  | CategorizationLearnerEntry
  | RatingLearnerEntry
  | NumericLearnerEntry
  | FormulaLearnerEntry
  | HotspotLearnerEntry
  | HighlightLearnerEntry

export type QuizRuntimeEntry = QuizPracticeEntry | QuizLearnerEntry

export interface QuizAuthoringValidationIssue {
  code: "missing-answer-key" | "invalid-answer-key" | "invalid-question"
  path: string
  message: string
}

export function toQuizLearnerEntry(entry: QuizAuthoringEntry): QuizLearnerEntry {
  const base = learnerBase(entry)

  switch (entry.type) {
    case QuizEntryType.SingleChoice:
      return {
        ...base,
        type: entry.type,
        options: cloneValue(entry.options),
      }

    case QuizEntryType.MultipleChoice:
      return withDefinedFields({
        ...base,
        type: entry.type,
        options: cloneValue(entry.options),
      }, {
        selectionLimit: cloneValue(entry.selectionLimit ?? entry.correctOptionIds.length),
      })

    case QuizEntryType.TrueFalse:
      return {
        ...base,
        type: entry.type,
      }

    case QuizEntryType.FillInTheBlank:
      return {
        ...base,
        type: entry.type,
        blanks: entry.blanks.map(toFillBlankLearnerField),
      }

    case QuizEntryType.ShortAnswer:
      return {
        ...base,
        type: entry.type,
      }

    case QuizEntryType.Essay:
      return withDefinedFields({
        ...base,
        type: entry.type,
      }, {
        minWordCount: cloneValue(entry.minWordCount),
        maxWordCount: cloneValue(entry.maxWordCount),
        showWordCount: cloneValue(entry.showWordCount),
      })

    case QuizEntryType.Matching:
      return withDefinedFields({
        ...base,
        type: entry.type,
        pairs: entry.pairs.map(({ id, left }) => ({ id, left })),
        rightOptions: rotateAnswerKeyFirstValues([
          ...entry.pairs.map((pair) => pair.right).filter(isNonEmptyString),
          ...(entry.distractors ?? []),
        ]),
      }, {
        allowPartialCredit: cloneValue(entry.allowPartialCredit),
      })

    case QuizEntryType.Ordering:
      return withDefinedFields({
        ...base,
        type: entry.type,
        items: entry.items.map(({ id, text }) => ({ id, text })),
      }, {
        allowPartialCredit: cloneValue(entry.allowPartialCredit),
      })

    case QuizEntryType.Categorization:
      return {
        ...base,
        type: entry.type,
        categories: cloneValue(entry.categories),
        items: entry.items.map(({ id, text }) => ({ id, text })),
      }

    case QuizEntryType.Rating:
      return {
        ...base,
        type: entry.type,
        scale: cloneValue(entry.scale),
      }

    case QuizEntryType.Numeric:
      // Numeric uses the formula as prompt data today, but removes tolerance
      // because tolerance is part of correctness.
      return withDefinedFields({
        ...base,
        type: entry.type,
        variables: cloneValue(entry.variables),
        formula: cloneValue(entry.formula),
        decimalPlaces: cloneValue(entry.decimalPlaces),
      }, {})

    case QuizEntryType.Formula:
      // Formula learner entries never include the hidden formula. A server prompt
      // can be added separately when grading is enabled.
      return withDefinedFields({
        ...base,
        type: entry.type,
        variables: cloneValue(entry.variables),
        decimalPlaces: cloneValue(entry.decimalPlaces),
      }, {})

    case QuizEntryType.Hotspot:
      return {
        ...base,
        type: entry.type,
        imageAssetUri: entry.imageAssetUri,
        imageWidth: entry.imageWidth,
        imageHeight: entry.imageHeight,
      }

    case QuizEntryType.Highlight:
      return {
        ...base,
        type: entry.type,
        plainText: entry.plainText,
      }
  }
}

export function toQuizLearnerEntries(entries: readonly QuizAuthoringEntry[]): QuizLearnerEntry[] {
  return entries.map(toQuizLearnerEntry)
}

export function validateQuizAuthoringEntry(entry: QuizAuthoringEntry): QuizAuthoringValidationIssue[] {
  const issues: QuizAuthoringValidationIssue[] = []
  validateAttachments(entry, issues)

  // This validates authored quiz completeness. It is not used to decide whether
  // an arbitrary runtime payload is trusted or locally gradable.
  switch (entry.type) {
    case QuizEntryType.SingleChoice: {
      const optionIds = new Set(entry.options.map((option) => option.id))
      if (!isNonEmptyString(entry.correctOptionId)) {
        addIssue(issues, "missing-answer-key", "correctOptionId", "Choose the correct option.")
      } else if (!optionIds.has(entry.correctOptionId)) {
        addIssue(issues, "invalid-answer-key", "correctOptionId", "The correct option must exist in options.")
      }
      break
    }

    case QuizEntryType.MultipleChoice: {
      const optionIds = new Set(entry.options.map((option) => option.id))
      if (!entry.correctOptionIds.length) {
        addIssue(issues, "missing-answer-key", "correctOptionIds", "Choose at least one correct option.")
      }
      for (const [index, optionId] of entry.correctOptionIds.entries()) {
        if (!optionIds.has(optionId)) {
          addIssue(issues, "invalid-answer-key", `correctOptionIds.${index}`, "Correct options must exist in options.")
        }
      }
      if (
        entry.selectionLimit !== undefined &&
        (!Number.isInteger(entry.selectionLimit) || entry.selectionLimit <= 0)
      ) {
        addIssue(issues, "invalid-question", "selectionLimit", "Selection limit must be a positive integer.")
      }
      break
    }

    case QuizEntryType.TrueFalse:
      if (typeof entry.correctAnswer !== "boolean") {
        addIssue(issues, "missing-answer-key", "correctAnswer", "Choose true or false as the correct answer.")
      }
      break

    case QuizEntryType.FillInTheBlank:
      if (!entry.blanks.length) {
        addIssue(issues, "missing-answer-key", "blanks", "Add at least one blank.")
      }
      entry.blanks.forEach((blank, index) => validateFillBlankField(blank, `blanks.${index}`, issues))
      break

    case QuizEntryType.ShortAnswer:
      if (!entry.acceptedAnswers.some(isNonEmptyString)) {
        addIssue(issues, "missing-answer-key", "acceptedAnswers", "Add at least one accepted answer.")
      }
      break

    case QuizEntryType.Essay:
      // Essays can be valid authoring entries without deterministic answer keys.
      break

    case QuizEntryType.Matching:
      if (!entry.pairs.length) {
        addIssue(issues, "missing-answer-key", "pairs", "Add at least one matching pair.")
      }
      entry.pairs.forEach((pair, index) => {
        if (!isNonEmptyString(pair.id)) addIssue(issues, "invalid-question", `pairs.${index}.id`, "Pair id is required.")
        if (!isNonEmptyString(pair.left)) addIssue(issues, "invalid-question", `pairs.${index}.left`, "Left item is required.")
        if (!isNonEmptyString(pair.right)) addIssue(issues, "missing-answer-key", `pairs.${index}.right`, "Right item is required.")
      })
      break

    case QuizEntryType.Ordering: {
      if (!entry.items.length) {
        addIssue(issues, "missing-answer-key", "items", "Add at least one ordering item.")
      }
      const positions = new Set<number>()
      entry.items.forEach((item, index) => {
        if (!isNonEmptyString(item.id)) addIssue(issues, "invalid-question", `items.${index}.id`, "Item id is required.")
        if (!isNonEmptyString(item.text)) addIssue(issues, "invalid-question", `items.${index}.text`, "Item text is required.")
        if (!Number.isInteger(item.correctPosition) || item.correctPosition < 0) {
          addIssue(issues, "missing-answer-key", `items.${index}.correctPosition`, "Correct position must be a non-negative integer.")
        } else {
          positions.add(item.correctPosition)
        }
      })
      if (positions.size !== entry.items.length) {
        addIssue(issues, "invalid-answer-key", "items", "Ordering positions must be unique.")
      }
      break
    }

    case QuizEntryType.Categorization: {
      const categoryIds = new Set(entry.categories.map((category) => category.id))
      if (!entry.categories.length) {
        addIssue(issues, "invalid-question", "categories", "Add at least one category.")
      }
      if (!entry.items.length) {
        addIssue(issues, "missing-answer-key", "items", "Add at least one categorization item.")
      }
      entry.items.forEach((item, index) => {
        if (!item.correctCategoryIds.length) {
          addIssue(issues, "missing-answer-key", `items.${index}.correctCategoryIds`, "Choose at least one correct category.")
        }
        for (const categoryId of item.correctCategoryIds) {
          if (!categoryIds.has(categoryId)) {
            addIssue(issues, "invalid-answer-key", `items.${index}.correctCategoryIds`, "Correct categories must exist.")
          }
        }
      })
      break
    }

    case QuizEntryType.Rating:
      if (entry.correctRating !== undefined) {
        const { min, max } = entry.scale
        if (!Number.isFinite(entry.correctRating) || entry.correctRating < min || entry.correctRating > max) {
          addIssue(issues, "invalid-answer-key", "correctRating", "Correct rating must be within the scale.")
        }
      }
      break

    case QuizEntryType.Numeric:
    case QuizEntryType.Formula:
      validateFormulaLikeEntry(entry, issues)
      break

    case QuizEntryType.Hotspot:
      if (!entry.imageAssetUri || !isAssetUri(entry.imageAssetUri)) {
        addIssue(issues, "invalid-question", "imageAssetUri", "Add an image before saving a hotspot question.")
      }
      if (!isPositiveNumber(entry.imageWidth) || !isPositiveNumber(entry.imageHeight)) {
        addIssue(issues, "invalid-question", "imageWidth", "Image dimensions must be positive.")
      }
      if (!entry.hotspots.length) {
        addIssue(issues, "missing-answer-key", "hotspots", "Add at least one hotspot.")
      }
      entry.hotspots.forEach((hotspot, index) => {
        if (!isFiniteInRange(hotspot.x, 0, 100) || !isFiniteInRange(hotspot.y, 0, 100)) {
          addIssue(issues, "invalid-answer-key", `hotspots.${index}`, "Hotspot coordinates must be percentages from 0 to 100.")
        }
        if (!hotspot.zones.length || hotspot.zones.some((zone) => !isPositiveNumber(zone.radius))) {
          addIssue(issues, "missing-answer-key", `hotspots.${index}.zones`, "Add at least one positive-radius zone.")
        }
      })
      break

    case QuizEntryType.Highlight:
      if (!isNonEmptyString(entry.plainText)) {
        addIssue(issues, "invalid-question", "plainText", "Highlight text is required.")
      }
      if (!entry.highlights.length) {
        addIssue(issues, "missing-answer-key", "highlights", "Mark at least one correct span.")
      }
      entry.highlights.forEach((highlight, index) => {
        if (!isValidHighlightSpan(highlight, entry.plainText.length)) {
          addIssue(issues, "invalid-answer-key", `highlights.${index}`, "Highlight spans must fit inside the plain text.")
        }
      })
      break
  }

  return issues
}

function validateAttachments(
  entry: QuizAuthoringEntry,
  issues: QuizAuthoringValidationIssue[],
): void {
  const groups = [
    ["learnerVisible", entry.attachments?.learnerVisible],
    ["authorOnly", entry.attachments?.authorOnly],
  ] as const
  for (const [group, attachments] of groups) {
    attachments?.forEach((attachment, index) => {
      if (!isAssetUri(attachment.assetUri)) {
        addIssue(
          issues,
          "invalid-question",
          `attachments.${group}.${index}.assetUri`,
          "Attachment must reference a managed asset.",
        )
      }
    })
  }
}

export function isCompleteQuizAuthoringEntry(entry: QuizAuthoringEntry): boolean {
  return validateQuizAuthoringEntry(entry).length === 0
}

function learnerBase(entry: QuizAuthoringEntry) {
  return withDefinedFields({
    stem: entry.stem,
    settings: cloneValue(entry.settings),
  }, {
    points: cloneValue(entry.points),
    feedback: entry.feedback?.general !== undefined
      ? { general: cloneValue(entry.feedback.general) }
      : undefined,
    attachments: entry.attachments?.learnerVisible?.length
      ? { learnerVisible: cloneValue(entry.attachments.learnerVisible) }
      : undefined,
  })
}

function toFillBlankLearnerField(blank: FillBlankField): FillBlankLearnerField {
  const base = {
    id: blank.id,
    position: blank.position,
  }

  switch (blank.input.type) {
    case FillBlankInputType.Text:
      return {
        ...base,
        input: { type: blank.input.type },
      }

    case FillBlankInputType.Number:
      return {
        ...base,
        input: withDefinedFields({ type: blank.input.type }, {
          requiredPrecision: cloneValue(blank.input.requiredPrecision),
          unit: cloneValue(blank.input.unit),
          requireUnit: cloneValue(blank.input.requireUnit),
          allowNegative: cloneValue(blank.input.allowNegative),
        }),
      }

    case FillBlankInputType.Dropdown:
      return {
        ...base,
        input: {
          type: blank.input.type,
          options: rotateAnswerKeyFirstValues(blank.input.options),
        },
      }

    case FillBlankInputType.WordBank:
      return {
        ...base,
        input: {
          type: blank.input.type,
          words: rotateAnswerKeyFirstValues(blank.input.words),
        },
      }
  }
}

function validateFillBlankField(
  blank: FillBlankField,
  path: string,
  issues: QuizAuthoringValidationIssue[],
): void {
  if (!isNonEmptyString(blank.id)) {
    addIssue(issues, "invalid-question", `${path}.id`, "Blank id is required.")
  }

  switch (blank.input.type) {
    case FillBlankInputType.Text:
      if (!blank.input.acceptedAnswers.some(isNonEmptyString)) {
        addIssue(issues, "missing-answer-key", `${path}.input.acceptedAnswers`, "Add at least one accepted answer.")
      }
      break

    case FillBlankInputType.Number:
      if (!Number.isFinite(blank.input.correctValue)) {
        addIssue(issues, "missing-answer-key", `${path}.input.correctValue`, "Add the correct numeric value.")
      }
      break

    case FillBlankInputType.Dropdown:
      // Authoring convention: the first option is the correct answer. Learner
      // payloads may also include options, so this rule is authoring-only.
      if (!isNonEmptyString(blank.input.options[0])) {
        addIssue(issues, "missing-answer-key", `${path}.input.options.0`, "Put the correct option first.")
      }
      break

    case FillBlankInputType.WordBank:
      // Authoring convention: the first word is the correct answer.
      if (!isNonEmptyString(blank.input.words[0])) {
        addIssue(issues, "missing-answer-key", `${path}.input.words.0`, "Put the correct word first.")
      }
      break
  }
}

function validateFormulaLikeEntry(entry: NumericEntry | FormulaEntry, issues: QuizAuthoringValidationIssue[]): void {
  if (!entry.variables.length) {
    addIssue(issues, "invalid-question", "variables", "Add at least one variable.")
  }
  entry.variables.forEach((variable, index) => {
    if (!isNonEmptyString(variable.name)) {
      addIssue(issues, "invalid-question", `variables.${index}.name`, "Variable name is required.")
    }
    if (!Number.isFinite(variable.min) || !Number.isFinite(variable.max) || variable.min > variable.max) {
      addIssue(issues, "invalid-question", `variables.${index}`, "Variable range must be valid.")
    }
  })
  if (!isNonEmptyString(entry.formula)) {
    addIssue(issues, "missing-answer-key", "formula", "Formula is required.")
  }
  if (!isPositiveOrZero(entry.tolerance)) {
    addIssue(issues, "invalid-answer-key", "tolerance", "Tolerance must be zero or greater.")
  }
}

function addIssue(
  issues: QuizAuthoringValidationIssue[],
  code: QuizAuthoringValidationIssue["code"],
  path: string,
  message: string,
): void {
  issues.push({ code, path, message })
}

function isNonEmptyString(value: unknown): value is string {
  return typeof value === "string" && value.trim().length > 0
}

function isPositiveNumber(value: unknown): value is number {
  return Number.isFinite(value) && Number(value) > 0
}

function isPositiveOrZero(value: unknown): value is number {
  return Number.isFinite(value) && Number(value) >= 0
}

function isFiniteInRange(value: unknown, min: number, max: number): value is number {
  return Number.isFinite(value) && Number(value) >= min && Number(value) <= max
}

function isValidHighlightSpan(span: HighlightSpan, textLength: number): boolean {
  return (
    Number.isInteger(span.start) &&
    Number.isInteger(span.end) &&
    span.start >= 0 &&
    span.end > span.start &&
    span.end <= textLength
  )
}

function rotateAnswerKeyFirstValues(values: readonly string[]): string[] {
  const clean = values.filter(isNonEmptyString)
  if (clean.length <= 1) return clean
  return [...clean.slice(1), clean[0]!]
}

function cloneValue<T>(value: T): T {
  if (value == null || typeof value !== "object") return value
  return JSON.parse(JSON.stringify(value)) as T
}

function withDefinedFields<T extends Record<string, unknown>>(
  base: T,
  fields: Record<string, unknown>,
): T {
  const next = { ...base }
  for (const [key, value] of Object.entries(fields)) {
    if (value !== undefined) next[key as keyof T] = value as T[keyof T]
  }
  return next
}
