import type { LearningCourseSummary } from '@/lib/courses';
import { Badge } from '@game-guild/ui/components/badge';
import { Button } from '@game-guild/ui/components/button';
import { ArrowRight, BookOpen, Star, Users } from 'lucide-react';
import Image from 'next/image';
import Link from 'next/link';

export function CourseCatalog({ courses }: { courses: LearningCourseSummary[] }) {
    return <div className="space-y-8"><header><p className="text-sm text-violet-300">Course catalog</p><h1 className="mt-1 text-3xl font-semibold">Find your next course</h1><p className="mt-2 max-w-2xl text-sm text-slate-400">Explore community-led programs. Enrollment and payment happen before classroom access is granted.</p></header>{courses.length === 0 ? <section className="border-y border-white/10 py-16 text-center"><BookOpen className="mx-auto size-8 text-slate-500" /><h2 className="mt-4 text-lg font-semibold">No courses are available right now</h2><p className="mt-2 text-sm text-slate-400">The catalog will update when new courses are published.</p></section> : <section className="grid gap-x-6 gap-y-8 sm:grid-cols-2 xl:grid-cols-3">{courses.map((course) => <article key={course.id} className="group min-w-0"><Link href={`/courses/${course.slug}`} className="block"><div className="relative aspect-video overflow-hidden rounded-md bg-white/[0.04]">{course.thumbnail ? <Image src={course.thumbnail} alt="" fill sizes="(min-width: 1280px) 30vw, (min-width: 640px) 50vw, 100vw" className="object-cover transition-transform group-hover:scale-[1.02]" /> : <div className="flex h-full items-center justify-center text-slate-600"><BookOpen className="size-9" /></div>}</div><div className="pt-4"><div className="flex gap-2"><Badge variant="outline">{course.category}</Badge><Badge variant="outline">{course.difficulty}</Badge></div><h2 className="mt-3 line-clamp-2 text-lg font-semibold group-hover:text-violet-300">{course.title}</h2><p className="mt-2 line-clamp-2 text-sm text-slate-400">{course.description}</p><div className="mt-3 flex gap-4 text-xs text-slate-500"><span className="flex items-center gap-1"><Users className="size-3.5" />{course.currentEnrollments}</span><span className="flex items-center gap-1"><Star className="size-3.5" />{course.averageRating.toFixed(1)}</span></div><Button variant="link" className="mt-2 h-auto p-0 text-violet-300">View course<ArrowRight className="ml-1 size-4" /></Button></div></Link></article>)}</section>}</div>;
}