import type { CourseAttendanceData } from '@/lib/courses';
import { Button } from '@game-guild/ui/components/button';
import { ArrowRight, BookOpen, Clock3 } from 'lucide-react';
import Image from 'next/image';
import Link from 'next/link';

export function LearnerDashboard({ learnerName, courses }: { learnerName: string; courses: CourseAttendanceData[] }) {
    if (courses.length === 0) {
        return <div className="space-y-8"><header><p className="text-sm text-violet-300">My learning</p><h1 className="mt-1 text-3xl font-semibold">Welcome back, {learnerName}</h1></header><section className="flex min-h-72 flex-col items-center justify-center border-y border-white/10 py-12 text-center"><div className="flex size-12 items-center justify-center rounded-lg bg-violet-500/10 text-violet-300"><BookOpen className="size-6" /></div><h2 className="mt-4 text-xl font-semibold">Your learning space is ready</h2><p className="mt-2 max-w-md text-sm text-slate-400">Enroll in a course to see lessons, deadlines, grades, and cohort activity here.</p><Button asChild className="mt-6"><Link href="/catalog">Explore the catalog</Link></Button></section></div>;
    }

    const active = courses.find((course) => course.currentItem) ?? courses[0];
    return <div className="space-y-8">
        <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-violet-300">My learning</p><h1 className="mt-1 text-3xl font-semibold">Welcome back, {learnerName}</h1><p className="mt-2 text-sm text-slate-400">Continue where you left off or review your current courses.</p></div><Button asChild variant="outline"><Link href="/catalog">Browse catalog</Link></Button></header>
        <section aria-labelledby="continue-heading" className="grid overflow-hidden border-y border-white/10 bg-white/[0.025] lg:grid-cols-[minmax(0,1fr)_20rem]">
            <div className="p-6 lg:p-8"><p className="text-xs font-medium uppercase text-violet-300">Continue learning</p><h2 id="continue-heading" className="mt-2 text-2xl font-semibold">{active.title}</h2><p className="mt-2 text-sm text-slate-400">{active.currentItem?.title ?? 'Open the classroom to continue.'}</p><div className="mt-6 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-violet-500" style={{ width: `${active.overallProgress}%` }} /></div><div className="mt-2 flex justify-between text-sm"><span className="text-slate-400">Course progress</span><span>{active.overallProgress}%</span></div><Button asChild className="mt-6"><Link href={`/courses/${active.slug}/content`}>Continue learning<ArrowRight className="ml-2 size-4" /></Link></Button></div>
            <div className="relative min-h-52 border-t border-white/10 bg-[#16171c] lg:border-l lg:border-t-0">{active.thumbnail ? <Image src={active.thumbnail} alt="" fill sizes="(min-width: 1024px) 20rem, 100vw" className="object-cover" /> : <div className="flex h-full items-center justify-center text-slate-600"><BookOpen className="size-12" /></div>}</div>
        </section>
        <section className="space-y-4"><div><h2 className="text-xl font-semibold">Current courses</h2><p className="text-sm text-slate-400">Only courses tied to your authenticated enrollment are listed.</p></div><div className="divide-y divide-white/10 border-y border-white/10">{courses.map((course) => <Link key={course.id} href={`/courses/${course.slug}`} className="grid gap-4 py-5 hover:bg-white/[0.025] sm:grid-cols-[minmax(0,1fr)_8rem_9rem] sm:items-center sm:px-3"><div className="min-w-0"><h3 className="truncate font-medium">{course.title}</h3><p className="mt-1 truncate text-sm text-slate-400">{course.currentItem?.title ?? `${course.completedItems} of ${course.totalItems} complete`}</p></div><div><p className="text-sm font-medium">{course.overallProgress}%</p><div className="mt-2 h-1.5 rounded-full bg-white/10"><div className="h-full rounded-full bg-violet-500" style={{ width: `${course.overallProgress}%` }} /></div></div><span className="flex items-center gap-2 text-sm text-slate-400"><Clock3 className="size-4" />{Math.ceil(course.remainingMinutes / 60)}h remaining</span></Link>)}</div></section>
    </div>;
}