<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation"/>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\GameGuild.SharedKernel\GameGuild.SharedKernel.csproj"/>
        <ProjectReference Include="..\GameGuild.Resources\GameGuild.Resources.csproj"/>
        <ProjectReference Include="..\GameGuild.Commerce.Core\GameGuild.Commerce.Core.csproj"/>
    </ItemGroup>

</Project>
