import type { TestCase, TestPlan } from 'emception';
import {
  generateDoctestHarness,
  type FunctionParameter as HarnessFunctionParameter,
  type FunctionalTestCase as HarnessFunctionalTestCase,
  type FunctionalTestSignature,
  type WorkspaceOverlayFile,
} from 'emception/testing';

import type {
  CodingAssessmentDefinition,
  CodingAssessmentParameter,
  CodingAssessmentTest,
} from './types';
import {
  ASSESSMENT_WORKSPACE_MOUNT,
  normalizeAssessmentWorkspacePath,
} from './paths';

export type AssessmentTestScope = 'public' | 'full';

/** A harness generated by this mapper is always textual C++ source. */
export interface AssessmentOverlayFile extends WorkspaceOverlayFile {
  readonly content: string;
}

/**
 * Generic runtime data derived from a GameGuild assessment definition.
 *
 * `plan` and `overlay` deliberately use only the public Emception contracts,
 * so callers can execute them through an `IdeController` or an Emception API
 * without wrapping or patching the vanilla IDE.
 */
export interface AssessmentExecutionPlan {
  readonly plan: TestPlan;
  readonly overlay: readonly AssessmentOverlayFile[];
  readonly weights: readonly number[];
}

function toHarnessParameter(
  parameter: CodingAssessmentParameter | { readonly Type: CodingAssessmentParameter['Type'] },
): HarnessFunctionParameter {
  return {
    type: `${parameter.Type.charAt(0).toUpperCase()}${parameter.Type.slice(1)}` as HarnessFunctionParameter['type'],
    content: 'Content' in parameter ? parameter.Content : undefined,
  };
}

function toPlanCase(
  test: CodingAssessmentTest,
  index: number,
  overlay: AssessmentOverlayFile[],
): TestCase {
  switch (test.kind) {
    case 'standard':
      return {
        kind: 'stdio',
        stdin: test.Stdin ?? '',
        expectedStdout: test.Stdout,
        expectedStderr: test.Stderr ?? undefined,
        expectedExit: test.ExitCode ?? undefined,
        weight: test.Weight,
        name: test.Name ?? undefined,
      };
    case 'functional': {
      if (test.Cases.length === 0) {
        throw new Error('FunctionalTestGroup requires at least one case');
      }

      const signature: FunctionalTestSignature = {
        functionName: test.Function.FunctionName,
        parameters: (test.Function.Parameters ?? []).map((parameter) => ({
          ...toHarnessParameter(parameter),
          name: parameter.Name,
        })),
        returnType: toHarnessParameter(test.Function.ReturnType),
      };
      const cases: HarnessFunctionalTestCase[] = test.Cases.map((testCase) => ({
        Inputs: testCase.Inputs.map(toHarnessParameter),
        Expected: toHarnessParameter(testCase.Expected),
      }));
      const harness = generateDoctestHarness(signature, cases, {
        index,
        name: test.Name ?? undefined,
      });
      const path = `${ASSESSMENT_WORKSPACE_MOUNT}/${harness.filename}`;
      overlay.push({ path, content: harness.source });

      return {
        kind: 'doctest',
        sourceFiles: [path],
        weight: test.Weight,
        name: test.Name ?? undefined,
      };
    }
  }
}

/**
 * Translates GameGuild's assessment DTO into the generic Emception test plan.
 *
 * Public scope is safe for learner-facing execution: it never reads private
 * test definitions. Full scope is intended for trusted author/grader views.
 */
export function buildAssessmentExecutionPlan(
  definition: CodingAssessmentDefinition,
  scope: AssessmentTestScope,
): AssessmentExecutionPlan {
  const tests = [
    ...(definition.Tests.Public ?? []),
    ...(scope === 'full' ? definition.Tests.Private ?? [] : []),
  ];
  const overlay: AssessmentOverlayFile[] = [];
  const cases = tests.map((test, index) => toPlanCase(test, index, overlay));
  const sources = Object.entries(definition.Data.Files)
    .filter(([, file]) => (file.Encoding ?? 'text') === 'text')
    .filter(([, file]) => scope === 'full' || file.Visibility !== 'Private')
    .map(([path]) => normalizeAssessmentWorkspacePath(path));

  if (scope === 'full') {
    for (const [path, file] of Object.entries(definition.Data.Files)) {
      if (file.Visibility === 'Private' && (file.Encoding ?? 'text') === 'text') {
        overlay.push({ path: normalizeAssessmentWorkspacePath(path), content: file.Content });
      }
    }
  }

  return {
    plan: { build: { sources }, cases },
    overlay,
    weights: cases.map((testCase) => testCase.weight ?? 1),
  };
}
