name: Close inactive issues
# triggers the workflow manually using the github UI
on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running the workflow'
        required: true
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-issue-stale: 30
          days-before-issue-close: 60
          stale-issue-message: "This issue is stale because it has been open for 30 days with no activity."
          close-issue-message: "This issue was closed because it has been inactive for 60 days since being marked as stale."
          days-before-pr-stale: 30
          days-before-pr-close: 60
          remove-issue-stale-when-updated: true
          remove-stale-when-updated: true


