name: Emception — Publish to npm

on:
  push:
    branches:
      - main
    # paths:
    #   - 'tools/emception/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Fetch all tags
        run: |
          git fetch --tags --force

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: tools/emception/package-lock.json

      - name: Install dependencies
        run: cd tools/emception && npm install

      - name: Build library
        run: cd tools/emception && npm run build:lib

      - name: Semantic Release
        run: npx semantic-release --extends ./tools/emception/.releaserc.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
