name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for reaching out and posting your first issue! We're thrilled to have you here and eager to assist you. Our team will look into your issue promptly and provide you with the best possible support. If you have any more questions or feedback, feel free to share. Happy gaming and coding!"
        pr-message: "Thank you for reaching out and posting your first PR! We're thrilled to have you here and eager to assist you. Our team will look into your issue promptly and provide you with the best possible support. If you have any more questions or feedback, feel free to share. Happy gaming and coding!"
