/**
 * Minimal curated emoji dataset (~150 entries) used by the
 * `EmojiPickerPlugin`. Mirrors the playground's `utils/emoji-list.ts`
 * shape but stripped to commonly-used glyphs to keep bundle size small.
 */
export type Emoji = {
  emoji: string
  aliases: string[]
  tags: string[]
}

const data: Emoji[] = [
  { emoji: "😀", aliases: ["grinning"], tags: ["smile", "happy"] },
  { emoji: "😃", aliases: ["smiley"], tags: ["happy", "joy", "haha"] },
  { emoji: "😄", aliases: ["smile"], tags: ["happy", "joy"] },
  { emoji: "😁", aliases: ["grin"], tags: ["happy"] },
  { emoji: "😆", aliases: ["laughing", "satisfied"], tags: ["happy", "haha"] },
  { emoji: "😅", aliases: ["sweat_smile"], tags: ["hot"] },
  { emoji: "🤣", aliases: ["rofl"], tags: ["lol", "laughing"] },
  { emoji: "😂", aliases: ["joy"], tags: ["tears", "lol"] },
  { emoji: "🙂", aliases: ["slightly_smiling_face"], tags: ["smile"] },
  { emoji: "🙃", aliases: ["upside_down_face"], tags: [] },
  { emoji: "😉", aliases: ["wink"], tags: ["flirt"] },
  { emoji: "😊", aliases: ["blush"], tags: ["proud"] },
  { emoji: "😇", aliases: ["innocent"], tags: ["angel"] },
  { emoji: "🥰", aliases: ["smiling_face_with_three_hearts"], tags: ["love"] },
  { emoji: "😍", aliases: ["heart_eyes"], tags: ["love", "crush"] },
  { emoji: "🤩", aliases: ["star_struck"], tags: ["eyes"] },
  { emoji: "😘", aliases: ["kissing_heart"], tags: ["love", "kiss"] },
  { emoji: "😗", aliases: ["kissing"], tags: ["3"] },
  { emoji: "😚", aliases: ["kissing_closed_eyes"], tags: [] },
  { emoji: "😙", aliases: ["kissing_smiling_eyes"], tags: [] },
  { emoji: "😋", aliases: ["yum"], tags: ["tongue", "lick"] },
  { emoji: "😛", aliases: ["stuck_out_tongue"], tags: [] },
  { emoji: "😜", aliases: ["stuck_out_tongue_winking_eye"], tags: ["prank"] },
  { emoji: "🤪", aliases: ["zany_face"], tags: ["goofy", "wacky"] },
  { emoji: "😝", aliases: ["stuck_out_tongue_closed_eyes"], tags: ["prank"] },
  { emoji: "🤑", aliases: ["money_mouth_face"], tags: ["rich"] },
  { emoji: "🤗", aliases: ["hugs"], tags: [] },
  { emoji: "🤭", aliases: ["hand_over_mouth"], tags: ["quiet", "whoops"] },
  { emoji: "🤫", aliases: ["shushing_face"], tags: ["silence", "quiet"] },
  { emoji: "🤔", aliases: ["thinking"], tags: ["hmmm"] },
  { emoji: "🤐", aliases: ["zipper_mouth_face"], tags: ["silence", "hush"] },
  { emoji: "🤨", aliases: ["raised_eyebrow"], tags: ["suspicious"] },
  { emoji: "😐", aliases: ["neutral_face"], tags: ["meh"] },
  { emoji: "😑", aliases: ["expressionless"], tags: [] },
  { emoji: "😶", aliases: ["no_mouth"], tags: ["mute", "silence"] },
  { emoji: "😏", aliases: ["smirk"], tags: ["smug"] },
  { emoji: "😒", aliases: ["unamused"], tags: ["meh"] },
  { emoji: "🙄", aliases: ["roll_eyes"], tags: [] },
  { emoji: "😬", aliases: ["grimacing"], tags: [] },
  { emoji: "🤥", aliases: ["lying_face"], tags: ["liar"] },
  { emoji: "😌", aliases: ["relieved"], tags: ["whew"] },
  { emoji: "😔", aliases: ["pensive"], tags: [] },
  { emoji: "😪", aliases: ["sleepy"], tags: ["tired"] },
  { emoji: "🤤", aliases: ["drooling_face"], tags: [] },
  { emoji: "😴", aliases: ["sleeping"], tags: ["zzz"] },
  { emoji: "😷", aliases: ["mask"], tags: ["sick", "ill"] },
  { emoji: "🤒", aliases: ["face_with_thermometer"], tags: ["sick"] },
  { emoji: "🤕", aliases: ["face_with_head_bandage"], tags: ["hurt"] },
  { emoji: "🤧", aliases: ["sneezing_face"], tags: ["achoo", "sick"] },
  { emoji: "🥵", aliases: ["hot_face"], tags: ["heat", "sweating"] },
  { emoji: "🥶", aliases: ["cold_face"], tags: ["freezing", "ice"] },
  { emoji: "🥴", aliases: ["woozy_face"], tags: ["groggy"] },
  { emoji: "😵", aliases: ["dizzy_face"], tags: ["dead", "knocked out"] },
  { emoji: "🤯", aliases: ["exploding_head"], tags: ["mind blown"] },
  { emoji: "🤠", aliases: ["cowboy_hat_face"], tags: [] },
  { emoji: "🥳", aliases: ["partying_face"], tags: ["celebration", "birthday"] },
  { emoji: "😎", aliases: ["sunglasses"], tags: ["cool"] },
  { emoji: "🤓", aliases: ["nerd_face"], tags: ["geek", "glasses"] },
  { emoji: "🧐", aliases: ["monocle_face"], tags: [] },
  { emoji: "😕", aliases: ["confused"], tags: [] },
  { emoji: "😟", aliases: ["worried"], tags: ["nervous"] },
  { emoji: "🙁", aliases: ["slightly_frowning_face"], tags: [] },
  { emoji: "☹️", aliases: ["frowning_face"], tags: [] },
  { emoji: "😮", aliases: ["open_mouth"], tags: ["surprise", "impressed", "wow"] },
  { emoji: "😯", aliases: ["hushed"], tags: ["silence", "speechless"] },
  { emoji: "😲", aliases: ["astonished"], tags: ["amazed", "gasp"] },
  { emoji: "😳", aliases: ["flushed"], tags: [] },
  { emoji: "🥺", aliases: ["pleading_face"], tags: ["puppy eyes"] },
  { emoji: "😦", aliases: ["frowning"], tags: [] },
  { emoji: "😧", aliases: ["anguished"], tags: ["stunned"] },
  { emoji: "😨", aliases: ["fearful"], tags: ["scared", "shocked", "oops"] },
  { emoji: "😰", aliases: ["cold_sweat"], tags: ["nervous"] },
  { emoji: "😥", aliases: ["disappointed_relieved"], tags: ["phew", "sweat"] },
  { emoji: "😢", aliases: ["cry"], tags: ["sad", "tear"] },
  { emoji: "😭", aliases: ["sob"], tags: ["sad", "cry", "bawling"] },
  { emoji: "😱", aliases: ["scream"], tags: ["horror", "shocked"] },
  { emoji: "😖", aliases: ["confounded"], tags: [] },
  { emoji: "😣", aliases: ["persevere"], tags: ["struggling"] },
  { emoji: "😞", aliases: ["disappointed"], tags: ["sad"] },
  { emoji: "😓", aliases: ["sweat"], tags: [] },
  { emoji: "😩", aliases: ["weary"], tags: ["tired"] },
  { emoji: "😫", aliases: ["tired_face"], tags: ["upset", "whine"] },
  { emoji: "🥱", aliases: ["yawning_face"], tags: [] },
  { emoji: "😤", aliases: ["triumph"], tags: ["smug"] },
  { emoji: "😡", aliases: ["rage", "pout"], tags: ["angry"] },
  { emoji: "😠", aliases: ["angry"], tags: ["mad", "annoyed"] },
  { emoji: "🤬", aliases: ["cursing_face"], tags: ["foul"] },
  { emoji: "😈", aliases: ["smiling_imp"], tags: ["devil", "evil", "horns"] },
  { emoji: "👿", aliases: ["imp"], tags: ["angry", "devil", "evil", "horns"] },
  { emoji: "💀", aliases: ["skull"], tags: ["dead", "danger", "poison"] },
  { emoji: "☠️", aliases: ["skull_and_crossbones"], tags: ["danger", "pirate"] },
  { emoji: "💩", aliases: ["poop", "shit", "hankey", "poo"], tags: [] },
  { emoji: "🤡", aliases: ["clown_face"], tags: [] },
  { emoji: "👹", aliases: ["japanese_ogre"], tags: ["monster"] },
  { emoji: "👺", aliases: ["japanese_goblin"], tags: [] },
  { emoji: "👻", aliases: ["ghost"], tags: ["halloween"] },
  { emoji: "👽", aliases: ["alien"], tags: ["ufo"] },
  { emoji: "👾", aliases: ["space_invader"], tags: ["game", "retro"] },
  { emoji: "🤖", aliases: ["robot"], tags: [] },
  { emoji: "❤️", aliases: ["heart"], tags: ["love"] },
  { emoji: "🧡", aliases: ["orange_heart"], tags: [] },
  { emoji: "💛", aliases: ["yellow_heart"], tags: [] },
  { emoji: "💚", aliases: ["green_heart"], tags: [] },
  { emoji: "💙", aliases: ["blue_heart"], tags: [] },
  { emoji: "💜", aliases: ["purple_heart"], tags: [] },
  { emoji: "🖤", aliases: ["black_heart"], tags: [] },
  { emoji: "🤍", aliases: ["white_heart"], tags: [] },
  { emoji: "🤎", aliases: ["brown_heart"], tags: [] },
  { emoji: "💔", aliases: ["broken_heart"], tags: ["sad"] },
  { emoji: "❣️", aliases: ["heavy_heart_exclamation"], tags: [] },
  { emoji: "💕", aliases: ["two_hearts"], tags: [] },
  { emoji: "💞", aliases: ["revolving_hearts"], tags: [] },
  { emoji: "💓", aliases: ["heartbeat"], tags: [] },
  { emoji: "💗", aliases: ["heartpulse"], tags: [] },
  { emoji: "💖", aliases: ["sparkling_heart"], tags: [] },
  { emoji: "💘", aliases: ["cupid"], tags: ["love", "heart"] },
  { emoji: "💝", aliases: ["gift_heart"], tags: ["chocolates"] },
  { emoji: "👍", aliases: ["+1", "thumbsup"], tags: ["approve", "ok"] },
  { emoji: "👎", aliases: ["-1", "thumbsdown"], tags: ["disapprove", "bury"] },
  { emoji: "👏", aliases: ["clap"], tags: ["praise", "applause"] },
  { emoji: "🙌", aliases: ["raised_hands"], tags: ["hooray"] },
  { emoji: "👐", aliases: ["open_hands"], tags: [] },
  { emoji: "🤝", aliases: ["handshake"], tags: ["deal"] },
  { emoji: "🙏", aliases: ["pray"], tags: ["please", "hope", "wish"] },
  { emoji: "✌️", aliases: ["v"], tags: ["victory", "peace"] },
  { emoji: "🤞", aliases: ["crossed_fingers"], tags: ["luck", "hopeful"] },
  { emoji: "🤟", aliases: ["love_you_gesture"], tags: [] },
  { emoji: "🤘", aliases: ["metal"], tags: [] },
  { emoji: "👌", aliases: ["ok_hand"], tags: [] },
  { emoji: "👈", aliases: ["point_left"], tags: [] },
  { emoji: "👉", aliases: ["point_right"], tags: [] },
  { emoji: "👆", aliases: ["point_up_2"], tags: [] },
  { emoji: "👇", aliases: ["point_down"], tags: [] },
  { emoji: "☝️", aliases: ["point_up"], tags: [] },
  { emoji: "✋", aliases: ["hand", "raised_hand"], tags: ["highfive", "stop"] },
  { emoji: "🤚", aliases: ["raised_back_of_hand"], tags: [] },
  { emoji: "🖐️", aliases: ["raised_hand_with_fingers_splayed"], tags: [] },
  { emoji: "🖖", aliases: ["vulcan_salute"], tags: ["prosper", "spock"] },
  { emoji: "👋", aliases: ["wave"], tags: ["goodbye"] },
  { emoji: "🤙", aliases: ["call_me_hand"], tags: [] },
  { emoji: "💪", aliases: ["muscle"], tags: ["flex", "bicep", "strong"] },
  { emoji: "🔥", aliases: ["fire"], tags: ["burn"] },
  { emoji: "⭐", aliases: ["star"], tags: [] },
  { emoji: "🌟", aliases: ["star2"], tags: [] },
  { emoji: "✨", aliases: ["sparkles"], tags: ["shiny"] },
  { emoji: "⚡", aliases: ["zap"], tags: ["lightning", "thunder"] },
  { emoji: "💥", aliases: ["boom", "collision"], tags: ["explode"] },
  { emoji: "💯", aliases: ["100"], tags: ["score", "perfect"] },
  { emoji: "✅", aliases: ["white_check_mark"], tags: [] },
  { emoji: "❌", aliases: ["x"], tags: [] },
  { emoji: "❓", aliases: ["question"], tags: ["confused"] },
  { emoji: "❗", aliases: ["exclamation", "heavy_exclamation_mark"], tags: ["bang"] },
  { emoji: "⚠️", aliases: ["warning"], tags: ["wip"] },
  { emoji: "🚀", aliases: ["rocket"], tags: ["launch", "ship"] },
  { emoji: "🎉", aliases: ["tada"], tags: ["hooray", "party"] },
  { emoji: "🎊", aliases: ["confetti_ball"], tags: [] },
  { emoji: "🎁", aliases: ["gift"], tags: ["present", "birthday"] },
  { emoji: "🏆", aliases: ["trophy"], tags: ["award", "contest", "winner"] },
  { emoji: "🥇", aliases: ["1st_place_medal"], tags: ["gold"] },
  { emoji: "🥈", aliases: ["2nd_place_medal"], tags: ["silver"] },
  { emoji: "🥉", aliases: ["3rd_place_medal"], tags: ["bronze"] },
  { emoji: "💡", aliases: ["bulb"], tags: ["idea"] },
  { emoji: "📌", aliases: ["pushpin"], tags: [] },
  { emoji: "📍", aliases: ["round_pushpin"], tags: [] },
  { emoji: "🔖", aliases: ["bookmark"], tags: [] },
  { emoji: "🔗", aliases: ["link"], tags: [] },
  { emoji: "🐛", aliases: ["bug"], tags: [] },
  { emoji: "🐞", aliases: ["beetle"], tags: [] },
  { emoji: "🚧", aliases: ["construction"], tags: ["wip"] },
]

export default data
